- src/Helper/GitHelper.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/Symfony.php
- tests/Local/LocalBuildTest.php
- tests/data/repositories/multiple/drupal/.platform.app.yaml
- tests/data/repositories/multiple/drupal/project.make
- tests/data/repositories/multiple/symfony/.platform.app.yaml
- tests/data/repositories/multiple/symfony/composer.json
> Build multiple apps

- src/Command/EnvironmentBranchCommand.php
- src/Command/EnvironmentCheckoutCommand.php
- src/Command/EnvironmentDeactivateCommand.php
- src/Command/EnvironmentDrushCommand.php
- src/Command/PlatformCommand.php
- src/Command/ProjectBuildCommand.php
- src/Command/ProjectDrushAliasesCommand.php
- src/Command/ProjectGetCommand.php
- src/Helper/DrushHelper.php
- src/Helper/FilesystemHelper.php
- src/Local/LocalBuild.php
- src/Local/LocalProject.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/Symfony.php
- src/Local/Toolstack/ToolstackBase.php
- tests/Helper/FilesystemHelperTest.php
> Refactoring for local project/filesystem info

- README.md
- composer.json
- composer.lock
- src/Application.php
- src/Command/IntegrationAddCommand.php
- src/Command/IntegrationCommand.php
- src/Command/IntegrationDeleteCommand.php
- src/Command/IntegrationGetCommand.php
- src/Command/IntegrationSetCommand.php
- src/Command/IntegrationUpdateCommand.php
- src/Model/HalResource.php
- src/Model/HalResourceInterface.php
- src/Model/Integration.php
Possible improvements:
* use a form interface ([matthiasnoback/symfony-console-form](/matthiasnoback/symfony-console-form)?) for filling in options
> Integration commands

- README.md
- src/Application.php
- src/Command/ActivityListCommand.php
- src/Command/ActivityLogCommand.php
- src/Model/Activity.php
- src/Model/Environment.php
- src/Model/HalResource.php
- src/Model/HalResourceInterface.php
This would help somewhat with #58 and #109
> Add environment:activities command.

- src/Command/IntegrationCommand.php
- src/Model/Integration.php
Should add support for generic web hook also updated https://github.com/OriPekelman/platformsh-docs/blob/blackfire/integration/webhooks.rst
> add support for generic webhook

- src/Command/ActivityListCommand.php
- src/Command/ActivityLogCommand.php
- src/Model/Activity.php
- src/Model/HalResource.php
... although it's probably more useful if I can get it to do this automatically after every environment action
> Auto-refresh the activity log.

- README.md
- services/accounts.php
- services/platform.php
- src/Application.php
- src/Command/ActivityListCommand.php
- src/Command/EnvironmentHttpAccessCommand.php
- src/Command/EnvironmentMetadataCommand.php
- src/Command/EnvironmentVariableDeleteCommand.php
- src/Command/EnvironmentVariableGetCommand.php
- src/Command/EnvironmentVariableSetCommand.php
- src/Command/PlatformCommand.php
- src/Model/Environment.php
- src/Model/HalResource.php
Re-opening #180 with the ability to set properties
> Add environment:metadata command

- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/Symfony.php
- src/Local/Toolstack/ToolstackBase.php
Uses the [`git check-ignore`](http://git-scm.com/docs/git-check-ignore/1.8.4) command
> Warn about non-ignored settings.local.php

- src/Application.php
- src/Command/EnvironmentBackupCommand.php
- src/Command/EnvironmentRestoreCommand.php
- src/Model/Activity.php
> Add restore command

- README.md
- src/Application.php
- src/Command/EnvironmentRelationshipsCommand.php
- src/Command/EnvironmentSqlCommand.php
- src/Command/EnvironmentSqlDumpCommand.php
- src/Util/RelationshipsUtil.php
Launch a MariaDB shell: `platform sql`
Execute a single statement: `platform sql "select * from users where name like 'alice'"`
Import local SQL file into the remote database: `platform sql < dump.sql`
Dump remote database to a local SQL file: `platform sql-dump`
> Add sql and sql-dump commands

- src/Command/EnvironmentSqlCommand.php
- src/Command/EnvironmentSqlDumpCommand.php
> Support postgres in SQL commands

- composer.json
- composer.lock
- src/Command/IntegrationCommand.php
Requires v0.1.3 of the client library
> Support BitBucket integration

- README.md
- src/Application.php
- src/Command/EnvironmentRelationshipsCommand.php
- src/Command/EnvironmentRoutesCommand.php
Requires an update to the client
> Add 'routes' command

- README.md
- src/Application.php
- src/Command/LocalBuildCommand.php
- src/Command/LocalCleanCommand.php
- src/Command/LocalDrushAliasesCommand.php
- src/Command/LocalInitCommand.php
Reduce confusion over the purpose of certain commands
> Create a local: command namespace

- src/Command/EnvironmentCheckoutCommand.php
- src/Command/PlatformLoginCommand.php
- src/Command/ProjectGetCommand.php
- src/Helper/GitHelper.php
- src/Local/LocalProject.php
This could allow users to have an 'origin' remote set to another URL.
[WIP]
> Ensure a Git remote named 'platform'.

- composer.json
- composer.lock
> Improve auto-completion

- src/Command/PlatformCommand.php
> Refactor cache

- src/Application.php
- src/Command/EnvironmentCheckoutCommand.php
- src/Command/EnvironmentSetRemoteCommand.php
- src/Command/PlatformCommand.php
- src/Helper/GitHelper.php
A workaround to compensate for the github integration problem: pull requests create `pr-123` branches which do not correspond to local branch names.
> Add environment:set-remote command

- src/Local/Toolstack/Composer.php
- tests/Local/Toolstack/ComposerTest.php
- tests/data/apps/fake-symfony/.platform.app.yaml
> Check again for the existence of composer.json

- README.md
- src/Command/PlatformCommand.php
> Proxy support

- src/Command/LocalBuildCommand.php
- src/Helper/FilesystemHelper.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Composer.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/NoToolstack.php
- src/Local/Toolstack/ToolstackBase.php
- tests/Local/LocalBuildTest.php
- tests/Local/Toolstack/VanillaTest.php
> Allow building without symlinks

- composer.json
- composer.lock
- src/Command/LocalBuildCommand.php
- src/Helper/DrushHelper.php
- src/Local/Toolstack/Drupal.php
- tests/Local/Toolstack/DrupalTest.php
- tests/data/apps/drupal/project-yaml/.platform.app.yaml
- tests/data/apps/drupal/project-yaml/project.make.yml
> Support YAML make files

- src/Exception/InvalidConfigException.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Composer.php
- tests/Local/Toolstack/ComposerTest.php
- tests/data/apps/deprecated-config/.platform.app.yaml
- tests/data/apps/drupal/project-yaml/.platform.app.yaml
- tests/data/apps/drupal/project/.platform.app.yaml
- tests/data/apps/fake-symfony/.platform.app.yaml
- tests/data/repositories/multiple/drupal/.platform.app.yaml
> Support new config format for type/flavor

- composer.json
- composer.lock
- src/Command/Auth/LoginCommand.php
- src/Command/WebCommand.php
> Switch to accounts URL

- src/Application.php
- src/Command/HasExamplesTrait.php
- src/Command/HelpCommand.php
- src/Command/ListCommand.php
- src/Command/PlatformCommand.php
- src/Console/CustomMarkdownDescriptor.php
- src/Console/CustomTextDescriptor.php
- src/Console/EventSubscriber.php
> Show examples in MD help

- src/Command/Environment/EnvironmentBackupCommand.php
This may not be possible in the API at the moment
> Allow listing more than 10 backups

- composer.json
- composer.lock
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommand.php
- src/Command/Integration/IntegrationUpdateCommand.php
Experimental
Advantages:
* unifies command options with interactively entered values; potential for interactivity on many commands with minimal code
* removes symfony/options-resolver dependency
* relatively lightweight and simple compared with symfony/form and symfony/options-resolver
* values are normalized *before* they are validated, unlike options-resolver
Todo:
> Form library

- README.md
- src/Application.php
- src/Command/PlatformCommand.php
- src/Command/Project/ProjectDeleteCommand.php
[![asciicast](https://asciinema.org/a/1kpqe5z38g4b12kp7yxxzwvkk.png)](https://asciinema.org/a/1kpqe5z38g4b12kp7yxxzwvkk)
> Add project:delete command

- composer.json
- composer.lock
- src/Command/Activity/ActivityLogCommand.php
- src/Command/Domain/DomainAddCommand.php
- src/Command/Domain/DomainDeleteCommand.php
- src/Command/Domain/DomainListCommand.php
- src/Command/Environment/EnvironmentActivateCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentDeleteCommand.php
- src/Command/Environment/EnvironmentHttpAccessCommand.php
- src/Command/Environment/EnvironmentInfoCommand.php
- src/Command/Environment/EnvironmentMergeCommand.php
- src/Command/Environment/EnvironmentSynchronizeCommand.php
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationDeleteCommand.php
- src/Command/PlatformCommand.php
- src/Command/Project/ProjectInfoCommand.php
- src/Command/Snapshot/SnapshotCreateCommand.php
- src/Command/Snapshot/SnapshotRestoreCommand.php
- src/Command/User/UserAddCommand.php
- src/Command/User/UserRoleCommand.php
- src/Command/Variable/VariableDeleteCommand.php
- src/Command/Variable/VariableSetCommand.php
- src/Util/ActivityUtil.php
> Handle new activities returned from httpaccess/smtp/variables

- .travis.yml
- composer.json
- composer.lock
This will be less important when #338 is done (we can package with specific versions)
> Test with normal 'composer install' too

- composer.json
- composer.lock
- src/Command/Activity/ActivityLogCommand.php
- src/Command/Domain/DomainAddCommand.php
- src/Command/Domain/DomainDeleteCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentHttpAccessCommand.php
- src/Command/Environment/EnvironmentInfoCommand.php
- src/Command/Environment/EnvironmentMergeCommand.php
- src/Command/Environment/EnvironmentSynchronizeCommand.php
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationDeleteCommand.php
- src/Command/PlatformCommand.php
- src/Command/Project/ProjectInfoCommand.php
- src/Command/User/UserAddCommand.php
- src/Command/User/UserDeleteCommand.php
- src/Command/User/UserRoleCommand.php
- src/Command/Variable/VariableDeleteCommand.php
- src/Command/Variable/VariableSetCommand.php
- src/Util/ActivityUtil.php
`user:delete` can return 0, 1, or multiple activities (deleting the user from whichever environments). This accommodates that case and other possible ones.
> Wait for multiple activities where applicable

- src/Command/Environment/EnvironmentBranchCommand.php
I expect no-one uses this, and if anyone does, then ` && platform build` works just as well
> Remove --build option for environment:branch

- README.md
- src/Command/Self/SelfUpdateCommand.php
Stop recommending Composer, as it causes problems with dependency conflicts.
> New installer instructions

- src/Command/PlatformCommand.php
- src/Command/Self/SelfUpdateCommand.php
Issue #339
It would be nice to have a new phar update library that handles version numbers correctly, doesn't require a hardcoded `exit`, and isn't abandoned. Could be a separate/follow-up issue.
> Check for updates automatically

- box.json
- composer.json
- composer.lock
- src/Command/PlatformCommand.php
- src/Command/Self/SelfUpdateCommand.php
- src/SelfUpdate/ManifestStrategy.php
> Change self-update method to remove abandoned library

- src/Command/Activity/ActivityListCommand.php
- src/Command/App/AppListCommand.php
- src/Command/Domain/DomainListCommand.php
- src/Command/Environment/EnvironmentInfoCommand.php
- src/Command/Environment/EnvironmentListCommand.php
- src/Command/Integration/IntegrationGetCommand.php
- src/Command/Project/ProjectInfoCommand.php
- src/Command/Project/ProjectListCommand.php
- src/Command/Snapshot/SnapshotListCommand.php
- src/Command/SubscriptionInfoCommand.php
- src/Command/User/UserListCommand.php
- src/Command/Variable/VariableGetCommand.php
- src/Util/Table.php
> Add --format option to 12 commands

- src/Command/CommandBase.php
- src/Command/Project/ProjectGetCommand.php
so I can run more copy-paste-friendly commands, e.g.:
```
platform app:config -p http://mybranch-myproject--myapp.eu.platform.sh/
```
or
```
platform app:config -p https://eu.platform.sh/projects/myproject/environments/mybranch
```
or
```
platform app:config -p eu.platform.sh/api/projects/myproject/environments/mybranch
```
> More project URL magic

- README.md
- src/Application.php
- src/Command/App/AppConfigGetCommand.php
- src/Command/Auth/LogoutCommand.php
- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentRelationshipsCommand.php
- src/Command/Local/LocalBuildCommand.php
- src/Command/Tunnel/TunnelCloseCommand.php
- src/Command/Tunnel/TunnelCommandBase.php
- src/Command/Tunnel/TunnelInfoCommand.php
- src/Command/Tunnel/TunnelListCommand.php
- src/Command/Tunnel/TunnelOpenCommand.php
- src/Util/PortUtil.php
- src/Util/ProcessManager.php
> SSH tunnels

- src/Command/Project/ProjectGetCommand.php
> Always fetch master if not specified in 'platform get'

- src/Command/Tunnel/TunnelOpenCommand.php
@OriPekelman is this wording OK?
> Allow SSH tunnels to master

- README.md
- composer.json
- composer.lock
- src/Command/Auth/LogoutCommand.php
- src/Command/CommandBase.php
A crossbreed between API tokens and refresh tokens
> Support exchangeable API tokens

- src/Command/Environment/EnvironmentLogCommand.php
- src/Command/Environment/EnvironmentSqlDumpCommand.php
> Enable SSH compression for sql-dump

- src/Command/Environment/EnvironmentSynchronizeCommand.php
> Provide more help for the synchronize command

- src/Command/Environment/EnvironmentSqlDumpCommand.php
> Include the project ID in the SQL dump filename

- composer.json
- composer.lock
Bumps PHP requirement to >= 5.5.9
> Upgrade to Symfony 3

- src/Local/Toolstack/Drupal.php
This means the build will be slightly more complex, but it will match what happens on Platform.sh more closely.
> Switch order of making files in the Drupal profile build

- tests/Local/LocalProjectTest.php
No source changes; only test changes to improve the CliConfig class coverage by forced config reset.
> Improve CliConfig coverage by forced config reset

- composer.json
- composer.lock
- src/Command/Activity/ActivityListCommand.php
- src/Command/Activity/ActivityLogCommand.php
- src/Command/CommandBase.php
> Adapt activity commands to show project activities

- src/Command/Tunnel/TunnelCloseCommand.php
- src/Command/Tunnel/TunnelCommandBase.php
- src/Command/Tunnel/TunnelInfoCommand.php
- src/Command/Tunnel/TunnelListCommand.php
- src/Command/Tunnel/TunnelOpenCommand.php
Addresses #446 
(but it's a bit ugly IMO)
> Show tunnel commands in the list; check support at 'runtime'

- src/Helper/FilesystemHelper.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/ToolstackBase.php
> Ensure old build is removed properly

- src/Api.php
- src/Application.php
- src/CliConfig.php
- src/Command/CommandBase.php
- src/Command/MultiCommand.php
- src/Command/Project/ProjectCreateCommand.php
- src/Command/Self/SelfInstallCommand.php
- src/Command/Tunnel/TunnelCommandBase.php
- src/Command/Tunnel/TunnelOpenCommand.php
- src/Util/ConsoleAnimation.php
- tests/CliConfigTest.php
- tests/data/mock-cli-config.yaml
- tests/data/mock-cli-user-config/config.yaml
> Add project:create command

- src/Local/LocalApplication.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Composer.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/NodeJs.php
- src/Local/Toolstack/Symfony.php
- src/Local/Toolstack/ToolstackBase.php
- tests/Local/LocalApplicationTest.php
- tests/Local/Toolstack/ComposerTest.php
- tests/Local/Toolstack/DrupalTest.php
- tests/data/apps/composer-mounts/.platform.app.yaml
- tests/data/apps/drupal/project/.platform.app.yaml
> Symlink all mounts, from the build to shared directories

- src/Helper/FilesystemHelper.php
- src/Local/LocalBuild.php
> Use chmod to force deleting builds even when files are read-only

- src/Command/User/UserRoleCommand.php
> Show roles on all environments in user:role

- src/Command/Local/LocalBuildCommand.php
- src/Local/LocalBuild.php
- src/Local/Toolstack/Composer.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/NodeJs.php
- src/Local/Toolstack/ToolstackBase.php
- src/Local/Toolstack/ToolstackInterface.php
Also a performance improvement for `platform build` (it doesn't need to look up the environment ID)
> LocalBuild clean up

- src/Command/Project/ProjectGetCommand.php
Something like this (might need a bit more refactoring)
> Ensure the project ID is written to config after 'get'

- dist/README.md
- dist/installer
- dist/manifest.json
> Installer fixes for Windows

- src/Command/Environment/EnvironmentCheckoutCommand.php
Tidies code, and removes a `git branch` and a `git ls-remote` in most cases.
> Refactor environment:checkout a bit

- src/Command/Local/LocalBuildCommand.php
- src/Local/LocalBuild.php
> Add --no-backup option to build command

- src/Command/Local/LocalBuildCommand.php
- src/Helper/GitHelper.php
- src/Local/LocalBuild.php
- src/Local/LocalProject.php
- src/Local/Toolstack/Drupal.php
- src/Local/Toolstack/ToolstackBase.php
- src/Local/Toolstack/ToolstackInterface.php
- tests/Helper/GitHelperTest.php
Provides a quick way to test a build based on the actual HEAD, excluding other files.
> Provide an option to clone to the build directory

- src/Command/Environment/EnvironmentDeleteCommand.php
> Allow deleting merged and inactive envs in one command

- src/Command/Environment/EnvironmentBranchCommand.php
I noticed that when you branch with platform, your local branch is not tracking. This adds the remote tracking.
> environment:branch to track upstream

- src/Command/CommandBase.php
- src/Console/CustomMarkdownDescriptor.php
- src/Console/CustomTextDescriptor.php
```
Usage: platform branch [--title TITLE] [--force] [-p|--project PROJECT] [--host HOST] [-e|--environment ENVIRONMENT] [--no-wait] [--] [<id>] [<parent>]
```
instead of:
```
Usage: environment:branch [--title TITLE] [--force] [-p|--project PROJECT] [--host HOST] [-e|--environment ENVIRONMENT] [--no-wait] [--] [<id>] [<parent>]
```
> Show alias and executable name in command synopsis

- src/Command/Db/DbDumpCommand.php
- src/Command/Db/DbSizeCommand.php
- src/Command/Db/DbSqlCommand.php
- src/Command/Environment/EnvironmentRelationshipsCommand.php
- src/Command/Tunnel/TunnelOpenCommand.php
- src/Helper/QuestionHelper.php
- src/Util/RelationshipsUtil.php
> Allow choosing a database via a --relationship command line option

- src/Command/Db/DbDumpCommand.php
- src/Local/Toolstack/Drupal.php
- src/Service/Git.php
> db:dump: add more advanced options

- README.md
- composer.lock
- src/Application.php
- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentCheckoutCommand.php
- src/Command/Project/ProjectGetCommand.php
- src/Command/Project/ProjectInfoCommand.php
- src/Command/Project/ProjectSetRemoteCommand.php
- src/Local/LocalProject.php
Addressing https://github.com/platformsh/platformsh-cli/issues/563#issuecomment-273426934 and other similar requests
> Add `project:set-remote` command

- src/Command/Db/DbDumpCommand.php
- src/Command/Project/ProjectGetCommand.php
- src/Local/BuildFlavor/Drupal.php
- src/Service/Filesystem.php
- tests/Helper/FilesystemHelperTest.php
- tests/Local/BuildFlavor/DrupalTest.php
- tests/Local/BuildFlavor/VanillaTest.php
> Relative paths should not depend on files already existing

- src/Command/Db/DbSizeCommand.php
> Exception if query fails in db:size

- src/Command/Server/ServerCommandBase.php
- src/Command/Tunnel/TunnelCommandBase.php
- src/Local/DependencyInstaller.php
- src/Service/Filesystem.php
- src/Service/Shell.php
- src/Service/Url.php
- src/Util/OsUtil.php
Also refactors URL opening and OS detection
> Fix URL opening on OS X

- src/Command/Activity/ActivityLogCommand.php
- src/Command/CommandBase.php
- src/Command/Db/DbSqlCommand.php
- src/Command/Environment/EnvironmentDrushCommand.php
- src/Service/Ssh.php
Enables colors for Behat and Symfony CLI, at least
> Use pseudo-terminal for SSH

- src/Command/Environment/EnvironmentSshCommand.php
- src/Service/Ssh.php
This fixes #590 , hope this does not introduce regressions with other usages of the `getSshArgs()` method 😕 
My very first contrib on this project, so I might miss something. 
I let you guys and CI tell me where I'm wrong 😄 👍
> Ssh issue with windows

- composer.json
- composer.lock
- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentDrushCommand.php
Release when API support is on all/most projects
> Find SSH apps via the new pf:ssh: URLs in the API

- src/Command/CommandBase.php
Makes it easier to run the CLI on Platform.sh environments themselves
> Populate project, environment, and app from environment variables where possible

- src/Service/Drush.php
> Use the local Drush if possible

- src/Command/Environment/EnvironmentDeleteCommand.php
> Add git prune help text when deleting a branch

- src/Command/Auth/LoginCommand.php
This is possible now that Platform.sh allows usernames. The usernames cannot be mistaken for email addresses.
> Support logging in with a username

- src/Command/Db/DbDumpCommand.php
> Fix exit code from db:dump to respect errors

- composer.lock
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
Depends on Platform.sh-Git version 2.7
> Add GitLab integration support

- src/Command/Mount/MountCommandBase.php
- src/Command/Mount/MountDownloadCommand.php
- src/Command/Mount/MountUploadCommand.php
>  mount commands: add --exclude and --include

- README.md
- composer.json
- composer.lock
- src/Application.php
- src/Command/Db/DbSizeCommand.php
- src/Command/Repo/CatCommand.php
- src/Command/Repo/LsCommand.php
- src/Command/Repo/ReadFileCommand.php
- src/Service/Api.php
> Use Git data API

- composer.json
- composer.lock
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationListCommand.php
- src/Command/Project/ProjectCreateCommand.php
[![asciicast](https://asciinema.org/a/ID15Ul48emxcQ3JskCV535OCJ.png)](https://asciinema.org/a/ID15Ul48emxcQ3JskCV535OCJ)
> Extended interactive question text (for integrations)

- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationUpdateCommand.php
- src/Console/EventSubscriber.php
This makes an effort to add webhooks, but fails gracefully (catches all exceptions with a message).
> Auto-ensure webhooks on GitHub and GitLab integrations

- src/SiteAlias/DrushAlias.php
> Fix existing aliases being prefixed with "@"

- src/Command/Integration/IntegrationCommandBase.php
* Set the push_events and merge_requests_events flags on new GitLab hooks.
* Update the configuration of GitLab and GitHub hooks if they need it.
> Ensure GitLab/GitHub hooks have the right events

- README.md
- composer.json
- composer.lock
- src/Application.php
- src/Command/Project/Variable/ProjectVariableDeleteCommand.php
- src/Command/Project/Variable/ProjectVariableGetCommand.php
- src/Command/Project/Variable/ProjectVariableSetCommand.php
- src/Command/Variable/VariableCommandBase.php
- src/Command/Variable/VariableCreateCommand.php
- src/Command/Variable/VariableDeleteCommand.php
- src/Command/Variable/VariableDisableCommand.php
- src/Command/Variable/VariableEnableCommand.php
- src/Command/Variable/VariableGetCommand.php
- src/Command/Variable/VariableListCommand.php
- src/Command/Variable/VariableSetCommand.php
- src/Command/Variable/VariableUpdateCommand.php
> Support new variable features

- src/Command/Db/DbSizeCommand.php
- src/Exception/InvalidConfigException.php
- src/Local/LocalApplication.php
- src/Util/YamlParser.php
- tests/Util/YamlParserTest.php
- tests/data/apps/complex-yaml/.platform.app.yaml
- tests/data/apps/complex-yaml/build-hook.sh
- tests/data/apps/complex-yaml/complex-app.yaml
- tests/data/apps/complex-yaml/location.yml
> Parse !include tags when loading a YAML file

- src/Application.php
- src/Command/CompletionCommand.php
- src/Command/Db/DbDumpCommand.php
- src/Command/Db/DbSizeCommand.php
- src/Command/Db/DbSqlCommand.php
- src/Command/Service/MongoDB/MongoDumpCommand.php
- src/Command/Service/MongoDB/MongoExportCommand.php
- src/Command/Service/MongoDB/MongoRestoreCommand.php
- src/Command/Service/MongoDB/MongoShellCommand.php
- src/Service/QuestionHelper.php
- src/Service/Relationships.php
> MongoDB commands

- src/Command/Db/DbDumpCommand.php
- src/Command/Db/DbSqlCommand.php
- src/Command/Environment/EnvironmentDrushCommand.php
- src/Command/Environment/EnvironmentLogCommand.php
- src/Command/Service/MongoDB/MongoDumpCommand.php
- src/Command/Service/MongoDB/MongoExportCommand.php
- src/Command/Service/MongoDB/MongoRestoreCommand.php
- src/Command/Service/MongoDB/MongoShellCommand.php
- src/Command/Service/RedisCliCommand.php
- src/Service/Relationships.php
- src/Util/OsUtil.php
- tests/Util/OsUtilTest.php
> Fix shell arg escaping with remote commands for Windows

- src/Command/Integration/IntegrationCommandBase.php
> Slack channel can be an ID

- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentActivateCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentCheckoutCommand.php
- src/Service/Api.php
> Make environment labels consistent

- composer.json
- composer.lock
- src/Command/Environment/EnvironmentActivateCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentMergeCommand.php
- src/Command/Environment/EnvironmentSynchronizeCommand.php
- src/Command/Snapshot/SnapshotCreateCommand.php
- src/Command/Snapshot/SnapshotRestoreCommand.php
- src/Service/Api.php
Based on https://github.com/platformsh/platformsh-client-php/commit/678f057067174c3b2c6716168bc86060a3f10097
> Always refresh resources when an operation is not available

- composer.json
- composer.lock
- src/Command/Snapshot/SnapshotListCommand.php
- src/Command/Snapshot/SnapshotScheduleAddCommand.php
- src/Command/Snapshot/SnapshotScheduleDeleteCommand.php
- src/Command/Snapshot/SnapshotScheduleListCommand.php
> Add snapshot:schedule commands

- composer.json
- composer.lock
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationUpdateCommand.php
- src/Service/PropertyFormatter.php
Bitbucket being a special snowflake, there is extra code needed to move the `key` and `secret` under the `app_credentials` structure.
> Add Bitbucket integration

- src/Command/Activity/ActivityListCommand.php
- src/Command/App/AppListCommand.php
- src/Command/Commit/CommitListCommand.php
- src/Command/Domain/DomainListCommand.php
- src/Command/Project/ProjectListCommand.php
- src/Command/Service/ServiceListCommand.php
- src/Command/User/UserListCommand.php
- src/Service/Table.php
- src/Util/Csv.php
- tests/Service/TableServiceTest.php
- tests/Util/CsvTest.php
> Add --columns option for all tables

- composer.json
- composer.lock
- src/Command/Snapshot/SnapshotRestoreCommand.php
Depends on
* deployment of platform.sh server version >= 2.10.x, and
* https://github.com/platformsh/platformsh-client-php/pull/26
> Allow restoring snapshots to another environment

- src/Command/Db/DbDumpCommand.php
- src/Command/Db/DbSizeCommand.php
- src/Command/Db/DbSqlCommand.php
- src/Service/QuestionHelper.php
- src/Service/Relationships.php
> Support multiple schemas per endpoint in DB commands

- src/SiteAlias/DrushAlias.php
Following on from https://github.com/platformsh/platformsh-cli/issues/772#issuecomment-464002857
> Use a different Drush alias root for site-local versions 8 or 9

- src/Command/Local/LocalDrushAliasesCommand.php
- src/Service/Drush.php
- src/Service/RemoteEnvVars.php
- src/SiteAlias/DrushAlias.php
> Attempt to find the app root via SSH for Enterprise environments

- src/Command/Activity/ActivityListCommand.php
- src/Command/Snapshot/SnapshotListCommand.php
Addresses issue #788 by @MacWeber
> Show a message if more snapshots/activities may be available

- composer.json
- composer.lock
- src/Command/Project/ProjectCreateCommand.php
Using https://github.com/platformsh/platformsh-client-php/commit/7905b8e84be3994714d765842c99f25397a225c9
> Make plans list dynamic in 'create' command

- src/Command/Environment/EnvironmentDrushCommand.php
The command escaping in the previous version did not account for Windows compatibility
> Make the --root argument static in Drush command

- src/Command/Self/SelfInstallCommand.php
> Default config file should be .bash_profile on OS X

- dist/installer.php
> Warn in installer about missing pcntl and posix extensions

- src/Service/Git.php
Theoretical fix, not tested yet.
> Fix GIT_SSH argument quoting

- src/Command/Db/DbSizeCommand.php
> Adding more precise dbsize

- .platform.app.yaml
- src/Command/App/AppConfigGetCommand.php
- src/Command/Environment/EnvironmentRelationshipsCommand.php
- src/Command/Route/RouteListCommand.php
- src/Command/WelcomeCommand.php
- tests/Command/App/AppConfigGetTest.php
- tests/Command/WelcomeCommandTest.php
Seems helpful since https://github.com/platformsh/platformsh-cli/releases/tag/v3.43.0
> Adapt welcome command for offline-on-container uses

- src/Model/Route.php
- src/Service/Api.php
> Prefer the primary route as the site URL

- src/Command/Db/DbSizeCommand.php
- src/Command/Mount/MountSizeCommand.php
Also makes column machine names consistent with the db:size command
> Rename "Capacity" to "% Used" in mount:size command

- README.md
- src/Application.php
- src/Command/Backup/BackupCreateCommand.php
- src/Command/Backup/BackupListCommand.php
- src/Command/Backup/BackupRestoreCommand.php
- src/Command/Environment/EnvironmentListCommand.php
- src/Console/CustomTextDescriptor.php
- src/Service/ActivityLoader.php
Matches naming in the API and the Management Console
Clearly some significant https://github.com/platformsh/platformsh-docs changes would be needed too
> [rfc] Rename snapshot -> backup

- src/Command/Db/DbDumpCommand.php
- src/Command/Db/DbSqlCommand.php
- src/Service/QuestionHelper.php
Fixes issue identified in #865 where default selection is not respected.
> Fix question helper

- src/Command/Local/LocalDrushAliasesCommand.php
- src/Service/Drush.php
- src/SiteAlias/DrushAlias.php
Original CLI issue: https://github.com/platformsh/platformsh-cli/issues/772
Drush fix: https://github.com/drush-ops/drush/pull/4019
> Remove drush-aliases SSH calls to find the absolute app root 

- src/Command/Environment/EnvironmentPushCommand.php
> Warn about pushing to branches named "production"

- .env-dist
- CONTRIBUTING.md
- Dockerfile
- docker-compose.yml
- docker/install_composer.sh
Simple  config for developing inside a docker container
> Added Docker setup

- src/Command/Local/LocalDrushAliasesCommand.php
- src/Service/Drush.php
- src/SiteAlias/DrushAlias.php
Reverts platformsh/platformsh-cli#869
> Revert "Remove drush-aliases SSH calls to find the absolute app root "

- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationDeleteCommand.php
Code source integrations can now change the URL (e.g. to GitHub)
> Update the project git URL when adding/deleting an integration

- dist/installer.php
> Installer: force self:install output to stdout

- src/Application.php
- src/Command/Environment/EnvironmentXdebugCommand.php
The new commands sets up a SSH tunnel for the Xdebug socket.
> feat(env): add e:xdebug command

- src/Command/Environment/EnvironmentXdebugCommand.php
> Ignore parse exceptions from xdebug command when loading command list

- src/Command/Server/ServerCommandBase.php
- src/Command/Tunnel/TunnelCommandBase.php
- src/Command/Tunnel/TunnelOpenCommand.php
- src/Command/Tunnel/TunnelSingleCommand.php
- src/Console/ProcessManager.php
- src/Service/Relationships.php
- tests/Command/Environment/EnvironmentRelationshipsTest.php
Clickable for http/https links
> Display tunnel details as a URL

- src/Command/Variable/VariableCommandBase.php
- src/Command/Variable/VariableCreateCommand.php
- src/Command/Variable/VariableUpdateCommand.php
Note: this disables interaction (if stdin is not a tty)
> Accept the variable value from stdin in variable:create and variable:update commands

- README.md
- src/Application.php
- src/Command/Integration/Activity/IntegrationActivityGetCommand.php
- src/Command/Integration/Activity/IntegrationActivityListCommand.php
- src/Command/Integration/Activity/IntegrationActivityLogCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationDeleteCommand.php
- src/Command/Integration/IntegrationGetCommand.php
- src/Command/Integration/IntegrationUpdateCommand.php
- src/Command/Integration/IntegrationValidateCommand.php
- src/Model/Activity.php
Long; probably needs refactoring
> Add integration:activity commands

- README.md
- config.yaml
- services.yaml
- src/ApiToken/CredentialHelperStorage.php
- src/ApiToken/FileStorage.php
- src/ApiToken/Storage.php
- src/ApiToken/StorageInterface.php
- src/Application.php
- src/Command/Auth/ApiTokenLoginCommand.php
- src/Command/Auth/BrowserLoginCommand.php
- src/Command/Auth/LogoutCommand.php
- src/Command/Auth/PasswordLoginCommand.php
- src/Command/CommandBase.php
- src/CredentialHelper/Manager.php
- src/CredentialHelper/SessionStorage.php
- src/Exception/LoginRequiredException.php
- src/Service/Api.php
- src/Service/Config.php
- src/Service/State.php
> Add API token login command

- composer.json
- composer.lock
- services.yaml
- src/Command/CommandBase.php
- src/Service/Api.php
> Automatically prompt for login when token refresh fails

- config.yaml
- src/Command/Integration/IntegrationCommandBase.php
The API now provides a sensible default
> Remove default From address for health.email notifications

- src/Command/Db/DbSizeCommand.php
This can't show the total allocated size (or the percentage), because that's only available in the API.
This also adds a --pipe option to output only the size estimate.
> Allow db:size command to work offline

- README.md
- src/Command/Environment/EnvironmentUrlCommand.php
- src/Command/Route/RouteGetCommand.php
- src/Command/Route/RouteListCommand.php
- src/Model/Route.php
- src/Service/Api.php
- tests/Command/Route/RouteListTest.php
Display the URL via, for example:
```sh
platform routes --columns route,type,to,url
```
> Sort routes, and optionally display the URL, in the route:list command

- README.md
ref https://github.com/platformsh/platformsh-cli/issues/955
This add more info on the readme about required extensions
Cheers
> README: add extensions needed by cli

- src/Command/CommandBase.php
- src/Service/QuestionHelper.php
> Provide autocomplete choice of projects if there are many

- dist/installer.php
> Add proxy support to the installer

- composer.json
- composer.lock
- src/Command/User/UserAddCommand.php
Allows sending an invitation even when a pending one exists for the same project & email address.
> Support force-sending an invitation

- src/Service/Shell.php
> Show the stderr of every shell command, if in debug mode

- src/Command/Service/MongoDB/MongoExportCommand.php
- src/Service/Relationships.php
Relates to (but doesn't solve) #978
> Misc MongoDB fixes for multi-instance setups

- dist/installer.php
Aids installation on Windows, where PHP comes with a list of extensions that are not enabled in the default php.ini file.
> Installer: auto-detect existing but disabled extensions

- src/Command/Tunnel/TunnelOpenCommand.php
- src/Command/Tunnel/TunnelSingleCommand.php
> Add --gateway-ports (-g) option to tunnel commands

- box.json
- vendor-bin/box/composer.json
- vendor-bin/box/composer.lock
> Fix build to include a .php8 file in symfony/polyfill-mbstring

- .github/dependabot.yml
Written according to https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates :crossed_fingers:
> Configure composer updates with Dependabot

- src/Command/Backup/BackupCreateCommand.php
This tones down the warning level on making such a backup. Live backups are useful.
> Rename the backup --unsafe option to --live

- dist/installer.php
- src/Service/Api.php
> Replace http->tcp and https->ssl in proxy URLs

- src/Service/Api.php
> Fix proxy settings in Api service

- composer.json
- composer.lock
- src/Command/Project/ProjectCreateCommand.php
> Add --default-branch option to the project:create command

- composer.json
- composer.lock
- src/Command/Variable/VariableCommandBase.php
- src/Command/Variable/VariableCreateCommand.php
> Support build-time environment-level variables

- composer.json
- composer.lock
- src/Command/Variable/VariableCreateCommand.php
> Explain the error about visible_build in the variable:create command

- composer.json
- composer.lock
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationListCommand.php
> Remove references to Hipchat

- src/Command/CommandBase.php
- src/Command/Project/ProjectListCommand.php
- src/Command/WelcomeCommand.php
- src/Util/Pager/Page.php
- src/Util/Pager/Pager.php
Something like this but it needs a refactor
> Paginate the projects list

- src/Command/CommandBase.php
Postponed until automated TLS redeploys + scheduled backups are generally available
> Add a warning when an API token is set on the container

- composer.json
- composer.lock
- src/Service/Api.php
Potentially addressing #754 (and duplicates #990 and #1083)
> Use composer/ca-bundle to set up CA certificates

- composer.json
- composer.lock
- src/Command/Integration/IntegrationAddCommand.php
- src/Command/Integration/IntegrationCommandBase.php
- src/Command/Integration/IntegrationUpdateCommand.php
- src/Command/Variable/VariableCreateCommand.php
Affects commands: `integration:add`, `integration:update`, `variable:create`, `variable:update`
Closes #1117
> Error when a conditional field is used in the wrong context

- src/Command/Project/ProjectGetCommand.php
> Display the error from Xcode in the project:get (get) command

- composer.json
- composer.lock
- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentLogCommand.php
- src/Command/Environment/EnvironmentScpCommand.php
- src/Command/Environment/EnvironmentSshCommand.php
- src/Command/Environment/EnvironmentXdebugCommand.php
- src/Command/Mount/MountDownloadCommand.php
- src/Command/Mount/MountUploadCommand.php
- src/Command/Tunnel/TunnelOpenCommand.php
- src/Command/Tunnel/TunnelSingleCommand.php
- src/Model/RemoteContainer/App.php
- src/Model/RemoteContainer/BrokenEnv.php
- src/Model/RemoteContainer/RemoteContainerInterface.php
- src/Model/RemoteContainer/Worker.php
> Add --instance (-I) option to SSH commands

- src/Command/Integration/IntegrationCommandBase.php
* Stop prompting for --message-format, --verify-tls and --facility.
* Make --syslog-host and --syslog-port required and remove the defaults.
* Validate that the port and facility are numeric strings (and convert to actual integers after validation).
* Prompt for the protocol before the host and port.
* Prompt for the auth mode before the auth token.
> Simplify prompts for the syslog and other log integrations

- README.md
- src/Application.php
- src/Command/Backup/BackupCreateCommand.php
- src/Command/CommandBase.php
- src/Command/Commit/CommitGetCommand.php
- src/Command/Environment/EnvironmentPushCommand.php
- src/Console/CustomTextDescriptor.php
- src/Console/HiddenInputOption.php
> Hide deprecated or confusing options from command help

- config.yaml
- src/Command/Auth/AuthInfoCommand.php
- src/Command/Project/ProjectCreateCommand.php
- src/Service/Api.php
Code changes required to verify a user's phone number with the KYC service before continuing with project creation. If a user is not verified, they are to be redirected to console's phone verification page.
> KYC Integration

- src/Command/Activity/ActivityListCommand.php
- src/Command/App/AppListCommand.php
- src/Command/Backup/BackupListCommand.php
- src/Command/Certificate/CertificateListCommand.php
- src/Command/Commit/CommitListCommand.php
- src/Command/Db/DbSizeCommand.php
- src/Command/Domain/DomainListCommand.php
- src/Command/Environment/EnvironmentListCommand.php
- src/Command/Integration/Activity/IntegrationActivityListCommand.php
- src/Command/Integration/IntegrationListCommand.php
- src/Command/Metrics/DiskUsageCommand.php
- src/Command/Mount/MountListCommand.php
- src/Command/Mount/MountSizeCommand.php
- src/Command/Organization/OrganizationListCommand.php
- src/Command/Organization/OrganizationSubscriptionListCommand.php
- src/Command/Organization/User/OrganizationUserListCommand.php
- src/Command/Project/ProjectListCommand.php
- src/Command/Route/RouteListCommand.php
- src/Command/Self/SelfStatsCommand.php
- src/Command/Service/ServiceListCommand.php
- src/Command/SshKey/SshKeyListCommand.php
- src/Command/User/UserListCommand.php
- src/Command/Variable/VariableListCommand.php
- src/Command/Worker/WorkerListCommand.php
- src/Console/ArrayArgument.php
- src/Service/Table.php
> Add help for --columns; add 'automated' column for backups

- src/Command/Environment/EnvironmentDeleteCommand.php
> Fix wildcard matching for environment:delete

- README.md
Wording matches that of our public docs[^1]
[^1]: https://docs.platform.sh/administration/cli.html
> Update README with new installation and upgrade methods

- src/Util/TimezoneUtil.php
- tests/Util/TimezoneUtilTest.php
- tests/data/tz
Fixes "Notice: date_default_timezone_set(): Timezone ID 'UTC0' is invalid"
> Fix parsing TZ environment variable

- config.yaml
- src/Command/CommandBase.php
- src/Command/Domain/DomainAddCommand.php
- src/Command/Domain/DomainCommandBase.php
- src/Command/Domain/DomainDeleteCommand.php
- src/Command/Domain/DomainGetCommand.php
- src/Command/Domain/DomainListCommand.php
- src/Command/Domain/DomainUpdateCommand.php
- src/Model/EnvironmentDomain.php
- src/Util/OsUtil.php
> Support environment-level domains

- composer.json
- composer.lock
- src/Application.php
- src/Command/Backup/BackupDeleteCommand.php
- src/Command/Backup/BackupGetCommand.php
> Add backup:get and backup:delete commands

- src/Command/HelpCommand.php
This also marks the "xml" help format as deprecated, and explains when the simplexml extension is not installed.
> Fix validation of --format when used with -h

- src/Command/CommandBase.php
- src/Command/Variable/VariableCreateCommand.php
- src/Command/Variable/VariableUpdateCommand.php
> Add --update option to variable:create (update if the variable exists)

- src/Command/HelpCommand.php
- src/Command/ListCommand.php
- src/Console/CustomJsonDescriptor.php
- src/Console/CustomMarkdownDescriptor.php
> Implement hidden aliases, options and namespaces in the JSON and Markdown formats for the list command

- config.yaml
- src/Command/Auth/VerifyPhoneNumberCommand.php
- src/Command/Project/ProjectCreateCommand.php
- src/Service/Api.php
Contained in this pull request are updates regarding verification and the KYC endpoints called.  
1. To test, first set a user as suspicious:
```
POST https://api.platform.sh/kyc/<UUID>/suspicious
BODY: {"suspicious":true,"notes":"Testing KYC","level":2}
```
2. Log into the suspicious account in your browser
3. Run `bin/platform logout`
4. Then `bin/platform login`
Make sure that you are logged into and authenticate the account that you marked suspicious previously
5. Run `bin/platform project:create`
> Update calls to KYC verification endpoint

- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Service/Api.php
> Remove --force option on the branch command

- composer.json
- composer.lock
- src/Command/Environment/EnvironmentActivateCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentDeleteCommand.php
- src/Command/Environment/EnvironmentInitCommand.php
- src/Command/Environment/EnvironmentMergeCommand.php
- src/Command/Environment/EnvironmentPauseCommand.php
- src/Command/Environment/EnvironmentPushCommand.php
- src/Command/Environment/EnvironmentRedeployCommand.php
- src/Command/Environment/EnvironmentResumeCommand.php
- src/Command/Environment/EnvironmentSynchronizeCommand.php
- src/Service/ActivityMonitor.php
> Handle multiple activities on environment actions

- composer.json
- composer.lock
- src/Command/Organization/User/OrganizationUserProjectsCommand.php
Shows the org name when running `org:user:projects --list-all`
> Add org metadata in org:user:projects command

- src/Service/ActivityMonitor.php
- Removes nonstandard abbreviation 'secs'
- Shows seconds regardless of elapsed time
> Improve elapsed time formatting for activities

- src/Service/ActivityMonitor.php
When grouping activities by status (integration vs non-integration):
- number the activities
- report all their statuses at the end
- make the status reporting consistent
- color the progress message according to the activity state
> Improve display of grouped activities

- src/Service/Config.php
Using the environment variable `CLI_CONFIG_FILE` the main configuration file can be specified, overriding the default: [`{CLI_ROOT}/config.yaml`](https://github.com/platformsh/legacy-cli/blob/main/config.yaml). This file is loaded before any other config and before the "user" config file and other environment variables.
This is to help with https://github.com/platformsh/cli/issues/81
We wouldn't want to recommend this for customer use, as it would be much harder to manage updates if the whole config was replaced at runtime.
> Allow the default config file to be replaced

- composer.json
- composer.lock
- src/Application.php
- src/Command/RuntimeOperation/ListCommand.php
- src/Command/RuntimeOperation/RunCommand.php
- src/Model/RemoteContainer/App.php
- src/Model/RemoteContainer/BrokenEnv.php
- src/Model/RemoteContainer/RemoteContainerInterface.php
- src/Model/RemoteContainer/Worker.php
> Support runtime operations

- config-defaults.yaml
- resources/oauth-listener/index.php
- src/Command/Auth/BrowserLoginCommand.php
Preview with:
```sh
php platform.phar login -f --browser=0
./bin/platform login -f --browser=0
```
and visit e.g. http://127.0.0.1:5000/?done or http://127.0.0.1:5000/?error
> Make the logo configurable for browser login

- composer.json
- composer.lock
- config-defaults.yaml
- config.yaml
- src/Service/Api.php
> Filter the projects list by vendor

- src/Command/Resources/ResourcesSetCommand.php
> Show the container profile name when setting profile sizes

- src/Command/Environment/EnvironmentPushCommand.php
> Add --resources-init option to the push command

- src/Command/Integration/IntegrationCommandBase.php
> Add --resources-init option for code source integrations

- src/Service/FileLock.php
> Use flock and fflush for locking

- src/Command/Variable/VariableCreateCommand.php
Relates to (currently reverted) #1335
> Fix: var:create --update not passing on --project option

- src/Command/Environment/EnvironmentLogCommand.php
- src/Service/RemoteEnvVars.php
- src/Util/StringUtil.php
- tests/Util/StringUtilTest.php
Ignores output from other processes during the SSH connection
Copies a method from the RemoteEnvVars class
> Fix invalid files being listed in "log" command

- src/Command/Activity/ActivityListCommand.php
- src/Command/Integration/Activity/IntegrationActivityListCommand.php
Adds columns: `time_execute`, `time_wait`, `time_build`, and `time_deploy` to the `activities` and `integration:activities` commands
> Add timing table columns for activity lists

- src/Command/Environment/EnvironmentHttpAccessCommand.php
I ended up testing this properly using the cli and all.
--
I haven't did a full tests of the project, I played with the code on
https://codesandbox.io/p/devbox/blissful-hill-56v4n9?file=%2Findex.php%3A33%2C1
> Support IPV6 ip address validation

- config-defaults.yaml
- src/Command/Project/ProjectCreateCommand.php
Effect combined with the Upsun config in https://github.com/platformsh/cli/pull/172:
> Highlight green regions in the project:create (create) command

- src/Command/Resources/ResourcesSetCommand.php
> Add "default" and "minimum" keywords for resources:set command options

- src/Command/Environment/EnvironmentSynchronizeCommand.php
- src/Util/StringUtil.php
Part of #1384 
Test for Upsun with:
```
curl -s https://raw.githubusercontent.com/platformsh/cli/main/internal/config/upsun-cli.yaml > /tmp/upsun-cli.yaml
curl -s https://pr-1401-e7q4ara-mpaw4nkgdwaea.eu-2.platformsh.site/platform.phar > /tmp/platform-pr-1401.phar
alias upsun='CLI_CONFIG_FILE=/tmp/upsun-cli.yaml php /tmp/platform-pr-1401.phar'
upsun sync
```
> Support "resources" in the environment:sync (sync) command

- src/Service/Ssh.php
The "default" identity files were not being added. They are needed where the URI may be external  (e.g. Bitbucket/GitHub/GitLab etc.) and when the user is not running an SSH agent. The problem was introduced in v4.12.0 (commit 3b8bfbf4fde63d15c9079986e6bf9dbbcd5f594f).
> Restore default identities when making an SSH connection

- src/Command/Backup/BackupCreateCommand.php
This confirm step is added because:
* The `backup` command has been run inadvertently by users who meant to run `backups` (to list backups).
* It can be surprisingly destructive: a backup will delete an older backup if the quota has been reached.
The above reasons are considered to outweigh a potential, but unlikely, backwards compatibility break. Scripts may block indefinitely after this change if they erroneously run `platform backup` in interactive mode. The solution is to disable interactive mode by adding the flag `--yes` or `-y` or `--no-interaction`, or by setting the environment variable `PLATFORMSH_CLI_NO_INTERACTION=1`.
> Add a confirm step before creating a backup

- config-defaults.yaml
- src/Command/Environment/EnvironmentPushCommand.php
Push options are supported since server version 23
> Use git push options always

- src/Command/Environment/EnvironmentPushCommand.php
This also removes the interactive questions for the environment parent and type.
> In the push command, do not set a parent if none is specified

- src/Command/Backup/BackupRestoreCommand.php
- src/Command/CommandBase.php
- src/Command/Environment/EnvironmentActivateCommand.php
- src/Command/Environment/EnvironmentBranchCommand.php
- src/Command/Environment/EnvironmentMergeCommand.php
- src/Command/Environment/EnvironmentPushCommand.php
`manual` will be removed in the API
> Remove "manual" value from --resources-init in 3 commands

- src/Command/Tunnel/TunnelOpenCommand.php
- src/Command/Tunnel/TunnelSingleCommand.php
Fixes https://github.com/platformsh/cli/issues/178 - a bug introduced in #1413 (versions: v4.15.3 / 5.0.11)
> Fix --gateway-ports option in tunnel commands

- src/Service/Api.php
During subscription loading the CLI was looking for an "organization_id" property of a project, when the property is named "organization". Additionally some backwards compatibility code can now be removed.
> Fix loading a subscription through the wrong org

- src/Command/Integration/Activity/IntegrationActivityListCommand.php
> Expose the integration:activities alias in help

- src/Command/Environment/EnvironmentPushCommand.php
An environment cannot be created via a push if the project's Git host is external. This would indicate that a code source integration is enabled on the project (e.g. with GitHub, GitLab or Bitbucket).
> Clarify that pushing cannot create an environment when the Git host is external

- .platform.app.yaml
- Dockerfile
- composer.json
- composer.lock
- scripts/test/build-and-install.sh
- src/Command/Self/SelfBuildCommand.php
- vendor-bin/box/composer.lock
* Use Composer 2 in dev builds
* Remove composer-bin-plugin
> Update dev build config

- src/Command/Activity/ActivityListCommand.php
We should live in the current decade Always. See: https://github.com/platformsh/platformsh-docs/pull/4461
> Update example date in ActivityListCommand

- composer.json
- composer.lock
Preliminary work for https://github.com/platformsh/legacy-cli/pull/1536
> Add symfony/var_dumper as dev dependency for debugging purpose
