src/Command/CompletionCommand.php
src/Command/EnvironmentActivateCommand.php
src/Command/EnvironmentBackupCommand.php
src/Command/EnvironmentBranchCommand.php
src/Command/EnvironmentDeactivateCommand.php
src/Command/EnvironmentDeleteCommand.php
src/Command/EnvironmentMergeCommand.php
src/Command/EnvironmentRelationshipsCommand.php
src/Command/EnvironmentSynchronizeCommand.php
src/Command/EnvironmentUrlCommand.php
src/Command/PlatformCommand.php

Adds an 'environment' argument (rather than an option) to these commands:
```
platform environment:activate [--environment my-env]
=> platform environment:activate [my-env] [my-env2] [my-env3] [...]
platform environment:backup [--environment my-env]
=> platform environment:backup [my-env]
platform environment:deactivate [--environment my-env]
=> platform environment:deactivate [my-env] [my-env2] [my-env3] [...]
platform environment:delete [--environment my-env]
=> platform environment:delete [my-env] [my-env2] [my-env3] [...]
platform branch new-env [--environment parent-env]
=> platform branch new-env [parent-env]
platform environment:merge [--environment my-env]
=> platform environment:merge [my-env]
```
Also allows the following commands to work with multiple environments:
* …

Add an environment argument to many commands

---

src/Command/ProjectBuildCommand.php
src/Command/ProjectCleanCommand.php
src/Command/ProjectGetCommand.php
src/Command/UrlCommandBase.php
src/Helper/FilesystemHelper.php
src/Helper/ShellHelper.php
src/Helper/ShellHelperInterface.php
src/Local/LocalBuild.php
src/Local/Toolstack/Drupal.php
src/Local/Toolstack/Symfony.php
src/Local/Toolstack/ToolstackBase.php
src/Local/Toolstack/ToolstackInterface.php
tests/Local/LocalBuildTest.php

Addresses my #179.
- the tar/untar commands need cross-platform testing:

Archive and re-use old builds if the app's files have not changed

---

src/Command/WelcomeCommand.php

It would be helpful to have the project URI and ID displayed whenever running the platform command within the context of a project.

Show more iformation in the welcome message for current project

---

src/Command/SshKeyAddCommand.php
src/Command/SshKeyDeleteCommand.php
src/Command/SshKeyListCommand.php

Based on Ori's work (https://github.com/platformsh/platformsh-cli/issues/74#issuecomment-65207224)
Type `platform ssh-key:add` (with no arguments) to generate an SSH key and add it to your Platform.sh account. This would save time for those who haven't memorised the appropriate `ssh-keygen` command.
If you include `--yes` then it will happen non-interactively - this may at least be useful in future for scripted use, particularly when we support multiple accounts.
You can still specify a path to your preferred public key as before: `platform ssh-key:add ~/.ssh/id_rsa.pub`

Generate an SSH key for the user

---

src/Application.php
src/Command/HelpCommand.php
src/CustomTextDescriptor.php

Again, it's not my fault... you do really need this much code just to override a small aspect of Symfony's behaviour.

Display the command name and aliases in the command's help.

---

src/Command/EnvironmentDrushCommand.php
src/Command/EnvironmentRelationshipsCommand.php
src/Command/EnvironmentSshCommand.php
src/Command/PlatformCommand.php
src/Model/Environment.php

[WIP] Allow SSH/drush into a specific remote app

---

README.md
src/Application.php
src/Command/EnvironmentBranchCommand.php
src/Command/PlatformCommand.php
src/Command/PlatformLoginCommand.php
src/Command/PlatformLogoutCommand.php
src/Command/WelcomeCommand.php
src/Helper/DrushHelper.php
tests/bootstrap.php

Changes configuration to use environment variables (removes `--session-id` option)
```bash
export PLATFORMSH_CLI_API_TOKEN=~/.my-api-token
platform projects
```

Support API tokens

---

src/Command/EnvironmentBranchCommand.php
src/Command/LocalDrushAliasesCommand.php
src/Command/PlatformCommand.php
src/Command/ProjectGetCommand.php
src/Command/WelcomeCommand.php
src/Local/LocalProject.php

* Default project directory will be a slug of the project title, instead of the ID.
* Default Drush alias group will be the same as the directory name.
* The created aliases are shown in the output of `get`.
* You can use `get` when the specified directory already exists (you will be asked if you want to overwrite it).
* Removed unnecessary `--include-inactive` option.

Improve 'platform get' UX

---

src/Command/Environment/EnvironmentUrlCommand.php

This adds an heuristic to look through the environment's routes to find an HTTPS URL.
... or perhaps this should wait until there is a way to specify a default route.

platform url should get the HTTPS URL of an environment

---

src/Command/Activity/ActivityListCommand.php
src/Command/Activity/ActivityLogCommand.php
src/Command/Environment/EnvironmentActivateCommand.php
src/Command/Environment/EnvironmentBranchCommand.php
src/Command/Environment/EnvironmentDeleteCommand.php
src/Command/Environment/EnvironmentHttpAccessCommand.php
src/Command/Environment/EnvironmentInfoCommand.php
src/Command/Environment/EnvironmentMergeCommand.php
src/Command/User/UserAddCommand.php
src/Util/ActivityUtil.php

* show a progress bar alongside the activity log, so user has feedback that polling is happening
* show activity state(s) in the progress bar, so the user understands what's pending
* advance the progress bar on every poll, not just when something changes (look lively)

Improve progress bars for activities

---

src/Command/Environment/EnvironmentDeleteCommand.php

Addresses issue #357.
Previously the remote Git branch would always be deleted if `--yes` was used
with the `environment:delete` command. Now it will only be deleted if the
option `--delete-branch` is appended.

Allow non-interactive choice about deleting branches

---

src/Command/Project/ProjectGetCommand.php

`platform get` appeared to expect a directory name, but it accepted a full path.
This PR fixes the resulting issue that Drush aliases were created with a full path as the group name (issue #364).

Issue #364: put default Drush alias group through basename()

---

src/Application.php

This is deprecated upstream in Symfony Console, it doesn't appear to be useful, and I haven't heard of anyone using it.

Remove deprecated 'shell' feature

---

src/Command/Environment/EnvironmentDeleteCommand.php
src/Helper/GitHelper.php

Finds merged remote branches on the `platform` Git remote, rather than local branches.

Improve environment:delete --merged

---

resources/console/dialogrc
src/Api.php
src/Application.php
src/Command/Activity/ActivityListCommand.php
src/Command/Activity/ActivityLogCommand.php
src/Command/CommandBase.php
src/Command/Environment/EnvironmentInfoCommand.php
src/Command/Environment/EnvironmentLogCommand.php
src/Command/Environment/EnvironmentSqlCommand.php
src/Command/Environment/EnvironmentSshCommand.php
src/Command/Integration/IntegrationGetCommand.php
src/Command/MultiAwareInterface.php
src/Command/MultiCommand.php
src/Command/Project/ProjectInfoCommand.php
src/Command/SubscriptionInfoCommand.php
src/Command/Tunnel/TunnelCommandBase.php
src/Helper/ArgvHelper.php

Add 'platform multi' command

---

src/Local/LocalBuild.php
src/Local/Toolstack/ToolstackBase.php
src/Local/Toolstack/ToolstackInterface.php

* Main advantage: confuses PhpStorm less (the build symlink is broken for a much shorter time)
* This was always my original intention, it got left out somehow...

Only remove the previous build when the new one completes

---

src/Exception/DependencyVersionMisMatchException.php
src/Helper/DrushHelper.php

* It caused problems, e.g. #463 
* We don't check for other dependency versions (npm, Composer, etc.)
* Eventually, we should be able to read the config and install/ensure build dependencies automatically where needed (#396)

Remove minimum Drush version check

---

src/Helper/DrushHelper.php

Should fix #477.
The previous logic was a bit recursive: it used `where drush` to find the path, and then `where <path>` to find whether the command exists. That at least made no sense on Windows.

Assume Drush is installed if the command resolved

---

bin/platform
composer.json

That way people don't get confusing syntax errors if they're on an ancient Mac with PHP 5.3 installed... (Not that I have seen someone do that, not at all...)

Explicitly check the PHP version when running the CLI tool

---

src/Command/Project/ProjectListCommand.php

Currently, the `project:list (projects)` command allows filtering by region (host). However, if your account holds hundreds of sites like mine, it becomes helpful to have a filter on the project title. This is how I have implemented it in my custom version of the CLI: very simply, the filter will show all projects that have a certain (sub)string in their title. The match is case insensitive by default and not configurable.
Thoughts?

Add 'title' filter to project:list

---

src/Command/Domain/DomainAddCommand.php
src/Command/Domain/DomainDeleteCommand.php
src/Command/Domain/DomainUpdateCommand.php
src/Command/Environment/EnvironmentActivateCommand.php
src/Command/Environment/EnvironmentDeleteCommand.php
src/Command/Environment/EnvironmentHttpAccessCommand.php
src/Command/Environment/EnvironmentInfoCommand.php
src/Command/Integration/IntegrationAddCommand.php
src/Command/Integration/IntegrationDeleteCommand.php
src/Command/Integration/IntegrationUpdateCommand.php
src/Command/Project/ProjectInfoCommand.php
src/Command/User/UserAddCommand.php
src/Command/User/UserDeleteCommand.php
src/Command/User/UserRoleCommand.php
src/Command/Variable/VariableDeleteCommand.php
src/Command/Variable/VariableSetCommand.php
src/Util/ActivityUtil.php

When waiting for 20 activities, this would reduce API calls from <= 20 on each check (every second) to <= ~11 on each.

Improve activities batch performance

---

src/Command/Environment/EnvironmentDeleteCommand.php

I think removing the remote branch by default when removing is dangerous. It's not often, but we are enforcing a feature-branching model, and it's possible that we would want some features to be kept remotely without an environment.
Also I noticed that although there are --yes, --no and --delete-branch, we don't really have a way to not delete it from the command line. So added that option as well.

Option for not deleting remote branch

---

src/Command/CommandBase.php
src/Command/Self/SelfUpdateCommand.php
src/SelfUpdate/SelfUpdater.php

Permit a command to continue after updating

---

src/Application.php
src/Command/Environment/EnvironmentDrushCommand.php
src/Command/Environment/EnvironmentSqlSizeCommand.php
src/Local/LocalApplication.php
src/Util/RelationshipsUtil.php

The `EnvironmentSqlSizeCommand` class is a little bit dirty, especially as it does not return the same data for MySQL and PostgreSQL.
I guessed two types of reports were sufficiant for the time being: Overview and Details. Detailed reports can be requested with `--details` option.
Out of the box, MySQL allows XML responses, so I added a `--xml` option for that. 
Review would be more than appreciated.
Thanks,
Branislav

Create CLI command for quick-read on SQL disk usage.

---

README.md

Unless PowerShell is supported, we better let user know we need linux/unix shell.

Add unix shell as requirement

---

composer.json
composer.lock
src/Application.php
src/Command/Project/Variable/ProjectVariableDeleteCommand.php
src/Command/Project/Variable/ProjectVariableGetCommand.php
src/Command/Project/Variable/ProjectVariableSetCommand.php

I have yet to try executing this code.  In theory, it should provide access to get/set/delete project-level variables, including the not-for-build and not-for-deploy flags.  It is dependent on this PR for the Client library:
https://github.com/platformsh/platformsh-client-php/pull/15

Add commands for project-level variables

---

src/Service/SelfUpdater.php

Platform.sh CLI occasionally checks for updates, even when `platform self:update` is not the command being run.
If the CLI is called from a custom script, then it isn't always clear that the message is about updating the platform.sh CLI tool.
Example:
We use [Docksal](http://docksal.io/) `fin` custom commands for for tasks such as dumping a DB from a platform.sh environment, and importing it into the local Docksal database container. It's a little bit confusing to type a `fin db-download master` command and see a message about checking for updates - is it updating `fin` or updating `platform`?
This PR adds the name "platform.sh CLI" to some of the SelfUpdate output messages:
- At the start of the output ("This instance of the platform.sh CLI ..." and "Checking for platform.sh CLI …

Clarify that self-update output messages are about platform.sh CLI

---

.travis.yml
config.yaml
services.yaml
src/Command/Local/LocalBuildCommand.php
src/Local/DependencyInstaller.php
src/Local/DependencyManager/Bundler.php
src/Local/DependencyManager/Composer.php
src/Local/DependencyManager/DependencyManagerBase.php
src/Local/DependencyManager/DependencyManagerInterface.php
src/Local/DependencyManager/Pip.php
src/Local/DependencyManager/Yarn.php
src/Local/LocalBuild.php
src/Service/Filesystem.php
tests/Local/Toolstack/BaseToolstackTest.php
tests/Local/Toolstack/DependenciesTest.php
tests/data/apps/build-deps/.platform.app.yaml

Install build-time dependencies

---

src/Command/Local/LocalBuildCommand.php
src/Local/DependencyInstaller.php
src/Local/DependencyManager/Bundler.php
src/Local/DependencyManager/Composer.php
src/Local/DependencyManager/DependencyManagerBase.php
src/Local/DependencyManager/DependencyManagerInterface.php
src/Local/DependencyManager/Npm.php
src/Local/DependencyManager/Pip.php
src/Local/DependencyManager/Yarn.php
src/Local/LocalBuild.php

This isn't the default, because many package managers just can't cope properly with global/system-wide installs, e.g. Composer.

Add an option to install dependencies globally

---

README.md
services.yaml
src/Application.php
src/Command/Environment/EnvironmentPushCommand.php
src/Command/Environment/EnvironmentRoutesCommand.php
src/Command/Environment/Route/RouteGetCommand.php
src/Service/Relationships.php
src/Service/Routes.php

```
$ platform environment:route:get
Enter a number to choose a route:
[0] https://{default}/
[1] http://{default}/
[2] http://www.{default}/
[3] https://www.{default}/
> 0
ssi:
enabled: false
original_url: 'https://{default}/'
upstream: php
cache:
default_ttl: 0
cookies:
- '*'
enabled: true
headers:
- Accept
- Accept-Language
type: upstream
url: 'https://my-branch-vgdzl2y-abcdef123456.eu.platform.sh/'
```

Add a command to view a resolved route of an environment

---

src/Application.php

PHP should be aware of the current timezone, so fallback to UTC would be implicit by using `date_default_timezone_get()`, because if `date.timezone` is not set in `php.ini`, default one is UTC.

Rely on date_default_timezone_get() instead of UTC fallback

---

src/Service/Config.php

When the `HOME` directory is not writable (e.g. on our environments), we end up spinning in the loop in `Config::canWriteDir` because of the failure to set `$current`.

Fix infinite loop in Config::canWriteDir

---

services.yaml
src/Command/Mount/MountCommandBase.php
src/Command/Mount/MountDownloadCommand.php
src/Command/Mount/MountListCommand.php
src/Command/Mount/MountUploadCommand.php
src/Local/LocalApplication.php
src/Service/Mount.php

The new style (available in an upcoming version, see https://github.com/platformsh/platformsh-docs/pull/688) broke `platform build` and the `mount` commands.

Support new mount style

---

src/Service/Drush.php
src/SiteAlias/DrushYaml.php

Support Drush 9.0.0-rc1 +

---

box.json
dist/installer.php
shell-config-bash.rc
shell-config.rc
src/Command/Self/SelfInstallCommand.php

* The slightly upgraded detection for ZSH means that `slimzsh` can be supported out of the box (without a `ZSH` environment variable).
* The refactoring means that such detection logic can be changed without having to alter the user's shell configuration file.
* Having the installer run `self:install` means that install logic can be specific to a CLI version.

Refactor shell config into separate files

---

src/Application.php
src/Command/Activity/ActivityListCommand.php
src/Command/Snapshot/SnapshotListCommand.php
src/Command/Snapshot/SnapshotRestoreCommand.php
src/Util/TimezoneUtil.php
tests/Util/TimezoneUtilTest.php

This preserves the system timezone detection, in case someone was relying on it, but also prioritizes `date.timezone` and the `TZ` environment variable (which are a lot easier for the user to control).

Respect date.timezone and allow TZ env var

---

README.md
src/Command/User/UserAddCommand.php
src/Command/User/UserListCommand.php
src/Command/User/UserRoleCommand.php

Example:
```
$ platform user:add user@example.com -r viewer -r master:viewer -r develop:contributor
Adding the user user@example.com to My Project (abcdef123456):
Project role: viewer
Role on develop: contributor
Role on master: viewer
Adding users can result in additional charges.
Are you sure you want to add this user? [Y/n] 
```

Improve user:add to allow setting roles on all environments

---

src/Command/Db/DbDumpCommand.php

* `--no-autocommit` causes problems with importing large tables into Galera
* `--opt` and `--quote-names` are enabled by default, so we do not need to specify them
* `--single-transaction` recommends `--quick`, but that is also enabled by `--opt`, which is default

[db:dump] Remove --no-autocommit and simplify mysqldump args

---

README.md
dist/installer.php
src/Command/Self/SelfInstallCommand.php

1. Avoid creating a new .bash_profile file (on Ubuntu this would override
.profile)
2. Allow the shell config selection to be overridden with a
PLATFORMSH_CLI_SHELL_CONFIG_FILE environment variable.

Installer: avoid creating a new .bash_profile file

---

src/Command/Db/DbDumpCommand.php

From the pg_dump manual on --no-owner (-O):
> Do not output commands to set ownership of objects to match the original
> database. By default, pg_dump issues ALTER OWNER or SET SESSION AUTHORIZATION
> statements to set ownership of created database objects. These statements will
> fail when the script is run unless it is started by a superuser (or the same
> user that owns all of the objects in the script). To make a script that can be
> restored by any user, but will give that user ownership of all the objects,
> specify -O.

[db:dump] Add --no-owner to pg_dump command

---

src/Command/Environment/EnvironmentBranchCommand.php

Context: https://platformsh.slack.com/archives/C0JHEUHQD/p1543336529859100?thread_ts=1543331516.850900&cid=C0JHEUHQD

[environment:branch] set the remote only for new branches

---

dist/installer.php

It is normally intended to be run via a pipe from `curl`, which means that
PHP's stdin isn't going to be a tty anyway.
This (hopefully) resolves an issue seen on RHEL installs.

Remove interactivity check from installer

---

composer.json
composer.lock
src/Command/Auth/BrowserLoginCommand.php

When already logged in and calling `platform login --force` with a new account, the command successfully logs in, and saves the access tokens in the persistent session. So far, so good. But when the command finishes, the magic destructor (`__destruct()`) is called on the old Connector object, which contains an old OAuth2Plugin object, which contains the old access/refresh tokens. The destructor then overwrites the session with the old tokens.
This commit ensures that the old Session and OAuth2Plugin instances are cleared (via `$connector->logOut()`) and it also ensures that old tokens are revoked.

Fix: browser login does not sufficiently log out from old account

---

src/Service/Drush.php
src/SiteAlias/DrushAlias.php
src/SiteAlias/DrushYaml.php
tests/Service/DrushServiceTest.php

- Use relative path for `root` (to account for differing app roots)
- A globally installed Drush 9 needs the aliases to be in `groupname.site.yml` (rather than `groupname.alias.yml`) but this isn't being picked up when in a particular site that uses Drush 8.
- Drush 9 has moved unknown keys such as `platformsh-cli-auto-remove` under an `options` key.
Todo:

Drush alias fixes

---

src/Command/Db/DbDumpCommand.php
src/Command/Db/DbSqlCommand.php
src/Service/Relationships.php
src/Service/RemoteEnvVars.php

For #779 
Enterprise databases have a different relationships structure with no service name and an endpoint exposed per schema per relationship.

Ensure the service name is in the relationship array

---

src/Service/Relationships.php

Using v3.40.2, we have the following issue when trying to run `platform service:mongo:export`:
I don't know if there is a test for this because I made a really quick fix, but this should do the work.

fix(mongo): database authentification

---

bin/platform
src/Command/Tunnel/TunnelOpenCommand.php

PHP bug 77260: https://bugs.php.net/bug.php?id=77260
Somehow this ini_set() doesn't fix the issue if it's included significantly later (but still before the `fork()`).
That leads me to suspect the introduction of other PCRE regexes before this line may reintroduce this bug, so this is fragile.
Addresses issue #774

Disable pcre.jit in tunnel:open command to work around PHP bug #77260

---

composer.json
composer.lock
src/Command/CommandBase.php
src/Command/Environment/EnvironmentLogCommand.php
src/Command/Environment/EnvironmentSshCommand.php
src/Command/Mount/MountCommandBase.php
src/Command/Mount/MountDownloadCommand.php
src/Command/Mount/MountListCommand.php
src/Command/Mount/MountSizeCommand.php
src/Command/Mount/MountUploadCommand.php
src/Local/LocalApplication.php
src/Model/SshDestination/App.php
src/Model/SshDestination/SshDestinationInterface.php
src/Model/SshDestination/Worker.php
src/Service/Mount.php

Resolves #797
* Adds the `--worker` option to all `mount` commands.
* Adds the `--worker` option to the `environment:logs` (`log`) command.
* Refactors worker selection in the `environment:ssh` (`ssh`) command.
* If `--app` or `--worker` is not provided, the above commands will now prompt the user to choose between the app(s) or their worker(s).
- The choices are filtered if either the app name or a non-qualified worker name is provided.
- If there is only one choice available, the prompt is skipped.

 Support --worker option for mount commands

---

src/Command/Db/DbDumpCommand.php

I was receiving this error while trying to dump by DB
```
> platform db:dump
Creating SQL dump file: dump.sql
mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' bytes when dumping table `cache_render` at row: 1024
```
max_allowed_packet is set in the DB service config but it isn't passed on to mysqldump. This patch passes the setting on and allows my dump to succeed

Pass max_allowed_packet setting to mysqldump

---

src/Util/YamlParser.php
tests/Util/YamlParserTest.php

The Symfony YAML parser doesn't handle this itself.
Apparently indenting the whole file is helpful for included files. It doesn't seem to be forbidden in the YAML spec, in fact the spec insists
> The amount of indentation is a presentation detail and must not be used to convey content information.

Accept wholly indented YAML files

---

composer.json
composer.lock
src/Application.php
src/Command/CommandBase.php
src/Command/Environment/EnvironmentRelationshipsCommand.php
src/Command/Route/RouteGetCommand.php
src/Command/Route/RouteListCommand.php
src/Command/Variable/VariableDecodeCommand.php
src/Model/Route.php
tests/Command/Environment/EnvironmentRelationshipsTest.php
tests/Command/Route/RouteGetTest.php
tests/Command/Route/RouteListTest.php
tests/Command/Variable/VariableDecodeTest.php

set. Simplicity for the end user at the expense of a little code complexity.

Add helpers to decode environment variables

---

src/Command/Environment/EnvironmentPushCommand.php

Allows a new environment to be created as an active branch from a specified
parent - thus inheriting settings from that parent - rather than setting the
parent later.

Add --branch option to push command

---

src/Command/Db/DbDumpCommand.php

```
curl https://pr-832-kgcph7y-mpaw4nkgdwaea.eu-2.platformsh.site/platform.phar -o ./platform.phar
php platform.phar db:dump --charset utf8mb4
```

Add --charset option to the db:dump command

---

.platform.app.yaml
dist/dev-build-index.php
dist/installer.php
src/Command/Self/SelfInstallCommand.php

The CLI won't work at all without the pcre or openssl extensions, so making this check required won't break BC.
Without the curl extension, most requests will still work, but it's more maintainable just to require it. Manual installation can still bypass this check.

Installer: require curl, openssl and pcre

---

services.yaml
src/Service/Drush.php
src/SiteAlias/DrushAlias.php
tests/Service/DrushServiceMock.php
tests/Service/DrushServiceTest.php

Now Drush aliases have the same URL that is used in the 'platform drush'
command. The deployment routes are filtered to only the 'upstream' routes that
match the app, then one is selected, preferring the primary route, and then
preferring HTTPS routes, and then preferring short URLs. If no route is found
the fallback is the environment's 'public-url' HAL link.
There could be a performance hit for new or updated environments as the
deployment resource will be fetched as well as the environment. But the API is
quite quick when a connection is already open, and deployments are cached
against the environment HEAD commit.
(the ugly part is that this introduces is another dependency on the Api service)

Use primary route URL from deployments API in Drush aliases

---

src/Command/Db/DbSizeCommand.php

some PE clusters do not have the  PROCESS privilege(s) and thus, have no access to the sys_tablespaces, revert to legacy way

bugfixing some PE customers

---

src/Command/Environment/EnvironmentPushCommand.php

Now --activate activates or branches before pushing.
The --branch option is no longer needed, so it's deprecated. It does the same thing as --activate.

Improve --activate in push command

---

src/Command/Environment/EnvironmentDrushCommand.php

Fix drush command quoting/escaping when a single quoted command is used

---

src/Command/CommandBase.php

This fixes the last problem identified in #865, `platform ssh --app myapp` does not actually select the application to connect to.

Allow --app option to correctly select application

---

src/Command/CommandBase.php

Fixes last remaining problem raised in #865 by disabling worker selection in enterprise environments.

Hide worker containers on enterprise

---

src/Command/Project/ProjectCreateCommand.php
src/Command/Project/ProjectSetRemoteCommand.php

After the project is created, it will be set as the local repository's "remote project", both as the Git remote (`platform`) and in the `.platform/local/project.yaml` file.

Add --set-remote option to project:create (create) command

---

services.yaml
src/Application.php
src/Command/Environment/EnvironmentScpCommand.php
src/Service/Scp.php

So, you currently have support for `ssh` and `mount:upload` and `mount:download`, but I find it more convenient if we could use more or less the scp syntax. Besides, the `mount` commands works on directories, making it impossible to upload/download single files.
The whole point with the `scp` command is to avoid  having to fetch the ssh url all the time, ie:
```
scp a.txt foobar2123123-master-7rqtwti--app@ssh.eu-2.platform.sh:var/upload
```
Instead, it is a simple as:
```
#upload
platform scp a.txt remote:var/upload
#upload multiple files
platform scp a.txt b.txt c.txt remote:var/upload
#download
platform scp remote:var/upload/a.txt .
```
I am aware of the  workaround given below, but I think supporting scp directly is way better
```
scp "$(platform ssh --pipe)":var/upload/a.txt .
```

Added support for scp

---

src/Command/Db/DbSizeCommand.php

Symptom:
```
ERROR 1054 (42S22) at line 1: Unknown column 'information_schema' in 'where clause'
```

Fix argument quoting in db:size on Windows

---

README.md
dist/installer.php
src/Command/Self/SelfInstallCommand.php
src/Command/SshKey/SshKeyAddCommand.php
src/Service/Config.php
src/Service/Drush.php
src/Service/Filesystem.php
src/Service/State.php
tests/ConfigTest.php
tests/Service/FilesystemServiceTest.php

Mainly intended to help in environments where a home directory may not be available.

Allow PLATFORMSH_CLI_HOME variable to override the home directory

---

src/Command/Db/DbSizeCommand.php
src/Model/Host/HostInterface.php
src/Model/Host/LocalHost.php
src/Model/Host/RemoteHost.php
src/Service/Shell.php

Quoting an SQL query inside a `mysql` command inside an `ssh` command on Windows appears to be too much trouble.

Pipe to command in db:size to avoid quoting issues on Windows

---

services.yaml
src/Command/Mount/MountDownloadCommand.php
src/Command/Mount/MountUploadCommand.php
src/Service/Rsync.php

This allows specifying an SSH key with the --identity-file (-i) option to the mount:download and mount:upload commands.
Resolves #880

Supply SSH options to mount:upload and mount:download commands

---

src/Command/Integration/IntegrationCommandBase.php

If username/repository doesn't work, we could go with a simplified version:
- user/repo
- username/repo
what do you think? Thanks!

replace foo/bar example with username/repository

---

src/Command/Environment/EnvironmentDeleteCommand.php

"Deactivate" is the mirror of "Activate," and is the terminology used in the UI anyway.

Add an alias for environment deactivation.

---

src/Command/User/UserAddCommand.php
src/Command/User/UserDeleteCommand.php

If redeploys are not automatically triggered, a warning is printed, e.g.:
```
User foo@example.com deleted
The remote environment(s) must be redeployed for the change to take effect.
To redeploy an environment, run: platform redeploy
```

Add redeploy warnings to the user:add and user:delete commands

---

resources/oauth-listener/index.php
src/Command/Auth/BrowserLoginCommand.php

This tells the server to prompt for re-authentication when the `--force` (`-f`) option is used with the `auth:browser-login` (`login`) command.

Support prompting for re-authentication in the login command

---

composer.json
composer.lock
src/Command/SshCert/SshCertLoadCommand.php
src/SshCert/Certifier.php

Regenerating RSA keys takes on average 200ms for me (between around 60ms and 400ms)
Regenerating ED25519 keys takes a small fraction of that, around ~1ms or less.
ED25519 was available from OpenSSH 6.5 (January 2014).
The CertificateFile option (which we are already using) was available from OpenSSH 7.2 (February 2016).

Use ed25519 SSH certificates/keys and regenerate keys every time

---

composer.json
composer.lock
config.yaml
src/Command/Auth/ApiTokenLoginCommand.php
src/Command/Auth/PasswordLoginCommand.php
src/Command/WebCommand.php
src/Command/WelcomeCommand.php
src/Service/Api.php
src/Service/Config.php

Removes `service.accounts_url` and `api.accounts_api_url` from `config.yaml`.
API access will instead be based on:
```yaml
api:
base_url: 'https://api.platform.sh'
oauth2_auth_url:  'https://auth.api.platform.sh/oauth2/authorize'
oauth2_token_url:  'https://auth.api.platform.sh/oauth2/token'
oauth2_revoke_url:  'https://auth.api.platform.sh/oauth2/revoke'
certifier_url: 'https://ssh.api.platform.sh'
```
Various user-facing URL strings are under `service`:
```yaml
service:
docs_url: 'https://docs.platform.sh'
docs_search_url: 'https://www.google.com/search?q=site%3Adocs.platform.sh%20{{ terms }}'
api_tokens_url: 'https://accounts.platform.sh/user/api-tokens'
register_url: 'https://auth.api.platform.sh'
reset_password_url: 'https://auth.api.platform.sh/reset-password'
console_url: …
```

Revamp config to no longer need an Accounts URL

---

src/Command/CommandBase.php
src/Command/SshCert/SshCertInfoCommand.php
src/Command/SshCert/SshCertLoadCommand.php
src/Service/Ssh.php
src/Service/SshConfig.php

Addresses #966 
- Skips adding SSH config/include files if the version is below 7.3 (and shows a message recommending 7.3+)
- Skips using `CertificateFile` if the version is below 7.2 (and shows a message recommending 7.3+)
- Fails to generate a certificate at all if the version is below 6.5 (and shows a message recommending 7.3+)

Detect the SSH version and show appropriate messages

---

src/Command/Project/Variable/ProjectVariableSetCommand.php
src/Command/Variable/VariableCreateCommand.php
src/Command/Variable/VariableDeleteCommand.php
src/Command/Variable/VariableUpdateCommand.php

Variable changes at the project level are going to generate activities, but environments are still not automatically redeployed. This PR removes the assumption that an activity is a redeploy. The "redeploy warning" will now be shown when project-level variables are changed or deleted, regardless of whether activities are generated.

Ignore project-level variable activities

---

src/SshCert/Certifier.php

Helps to identify the origin of the key in the output of `ssh-add -l`

Add a comment to auto-generated temporary SSH keys

---

config.yaml
src/SshCert/Certifier.php

Add this to the user config file to restore the old behavior (automatically add keys/certificates to the SSH agent):
```yaml
api:
add_to_ssh_agent: true
```

Disable use of SSH agent unless explicitly enabled in the user config file

---

.github/workflows/ci.yml

This PR adds Github Actions workflow to build the platform CLI phar executable file. The build steps are taken from [.gitlab-ci.yml](https://github.com/platformsh/platformsh-cli/blob/master/.gitlab-ci.yml) with minor tweaks to work with Github Actions.
```
- name: Build platform.phar
env:
CI_COMMIT_SHA: ${{ github.event.after }}
CI_COMMIT_REF_NAME: ${{ github.head_ref }}
run: |
CI_COMMIT_SHORT_SHA=$(echo $CI_COMMIT_SHA | head -c8)
./bin/platform self:build --no-composer-rebuild --yes --replace-version "$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" --output platform.phar
```

Github Actions workflow to build platform.sh CLI phar executable

---

src/Service/SshDiagnostics.php

This occurs if the SSH key or certificate was correct, but the requested service does not exist or the user does not have access to it.

Do not display "You probably need to add an SSH key" if the authentication succeeded

---

src/Exception/ProcessFailedException.php
src/Service/Git.php
src/Service/Shell.php

This improves the 'get' command error message when Git is not installed.

Fix missing Git detection on Windows

---

src/Service/SshConfig.php

This PR is based on a bug found running the CLI inside GitHub Actions:
1. The Platform.sh CLI passes certificate/key filenames to ssh using `%d` to substitute for the home directory, mostly for neatness, and to bypass some shell path quoting issues on Windows (e.g. when the user name contains a space) (https://github.com/platformsh/platformsh-cli/blob/fbb54779c624be881a35ce82da53df07141513ce/src/Service/SshConfig.php#L136-L138)
2. GitHub Actions sets the home directory via the `$HOME` environment variable to `/github/home`
3. The Platform.sh CLI reads `$HOME` as you'd expect
4. However, ssh (OpenSSH) picks up the home directory using's C's `getpwuid(getuid())`, which uses the user database (`/etc/passwd`) directly, and it ignores the `$HOME` environment variable: …

Stop using SSH home directory substitution

---

src/Service/ActivityMonitor.php

This is necessary for Testbed which can be slower.
cc @Rivee

Increase timeout when fetching activity logs

---

composer.json
composer.lock
src/Application.php
src/Command/Activity/ActivityCancelCommand.php
src/Command/Activity/ActivityGetCommand.php
src/Command/Activity/ActivityListCommand.php
src/Command/Activity/ActivityLogCommand.php
src/Command/Backup/BackupListCommand.php
src/Command/Backup/BackupRestoreCommand.php
src/Command/Integration/Activity/IntegrationActivityListCommand.php
src/Service/ActivityLoader.php
src/Service/ActivityMonitor.php

 Add activity:cancel command

---

src/Command/Integration/IntegrationAddCommand.php
src/Command/Integration/IntegrationCommandBase.php

The API used to provide the token in the GET response. It now hides it, so we need to use the value the user provided on the command line when the integration was created.
This helps with creating webhooks when a GitLab or GitHub integration is added.
In the longer term, the API should be upgraded to handle webhooks itself.

integrations: Pass the user-supplied token for creating webhooks

---

src/Service/Table.php
src/Util/Csv.php
src/Util/PlainFormat.php
tests/Util/CsvTest.php

Intended for easy parsing with `grep` / `cut` etc., at the expense of losing newlines/tabs within cells.
Inspired by https://clig.dev/#output

Add --format=plain option for table commands

---

src/Service/ActivityMonitor.php

This works around the ValueError, "Cannot cast a filtered stream on this system"
Closes #1027

Fix activity log in PHP 8

---

src/Command/Db/DbSizeCommand.php

It is possible in an edge situation that the --cleanup flag proposes to ALTER the information_schema tables. Since those cannot be OPTIMIZED, or ALTERED this isn't supposed to happen.
I propose to add a TABLE_TYPE="base table" (as per docs : https://dev.mysql.com/doc/refman/5.7/en/information-schema-tables-table.html ) so that it only lists actual tables, and never SYSTEM VIEW tables.

Fix edge case bug

---

src/CredentialHelper/Manager.php

https://github.com/docker/docker-credential-helpers/releases/tag/v0.6.4

Update docker-credential-helpers; add Keychain support for Mac M1

---

composer.json
composer.lock
src/Command/Environment/EnvironmentBranchCommand.php
src/Command/Environment/EnvironmentInfoCommand.php
src/Command/Environment/EnvironmentListCommand.php
src/Command/Environment/EnvironmentPushCommand.php
src/Command/User/UserAddCommand.php
src/Service/Api.php

- Allow listing types?? (there are just the 3 hardcoded ones for now, `development`, `staging` and `production`)

Support environment types

---

src/Service/CurlCli.php

Makes curl return an error exit code (22) and no output, if the HTTP response status code is >= 400

Pass --fail to curl utility commands

---

src/Command/Environment/EnvironmentDeleteCommand.php
src/Service/Git.php
tests/Service/GitServiceTest.php

This slightly changes behavior:
```sh
platform environment:delete --merged main
```
Previously: this deletes environments merged with the `main` environment (excluding `main` itself). Not specifying `main` would cause an error if no base environment was otherwise selected.
Now: this deletes environments merged with their _own_ parent, whatever that may be, including `main` if `main` itself has a parent and is merged. Not specifying `main` makes no difference.
I expect this change is unlikely to be disruptive, because the default branch is unlikely to have a parent. Environments with children will not be deleted in any case.
This improves performance, by a few seconds for the CLI project, and simplifies the code considerably.

Rework environment:delete --merged to not require a local Git repository

---

src/Command/Project/ProjectGetCommand.php
src/Service/Git.php

Changing 'master' to project->default_branch so we don't mention master if they specified something else.
Also, attempt to move to the correct branch after the init.

Removing 'master' in platform get command

---

config.yaml

Now that the docs site has a [dedicated page for search](https://docs.platform.sh/search.html?q=CLI), it might be nice to direct people there rather than a Google search.

:sparkles: Direct docs search to docs site

---

bin/platform

Remove workaround for an old PHP pcre.jit bug, fixed since PHP 7.3.11

---

dist/installer.php
src/CredentialHelper/Manager.php
src/SelfUpdate/ManifestStrategy.php
src/Service/Api.php
src/Service/Config.php
src/Service/SelfUpdater.php

3 places this was not being used:
1. the installer (needs a copied version of the function)
2. the credential helper download
3. the self-updater (manifest and phar download) (#986)

Use CA bundle detection everywhere else

---

src/Command/Backup/BackupListCommand.php

A partial version of https://github.com/platformsh/platformsh-cli/pull/1089
and the API seems only to list restorable backups, so that may help with #1114 without needing to add another option
The `backup:restore` command would still be activity-based (i.e. it couldn't filter by restorable backups); this MR only changes the `backup:list` (`backups`) command.

Use the newer backups API - for listing only

---

src/Command/Activity/ActivityGetCommand.php
src/Command/Activity/ActivityListCommand.php
src/Command/Activity/ActivityLogCommand.php
src/Command/CommandBase.php
src/Command/Environment/EnvironmentDeleteCommand.php
src/Command/Integration/Activity/IntegrationActivityListCommand.php
src/Console/ArrayArgument.php
src/Service/ActivityLoader.php

* Add --type and --exclude-type options
* Include the environment(s) specified by ID, even when --inactive or --merged are also specified
* Split the environment value by commas, in the 'environment' argument (when a single value is given)
* Make the reason for environments being found clearer
* Handle all environment statuses

Improve environment:delete command

---

src/Command/Environment/EnvironmentPushCommand.php
src/Command/User/UserAddCommand.php
src/Service/Api.php
tests/Command/User/UserAddCommandTest.php

Currently, in non-interactive mode, the `user:add` and `user:update` commands support adding users to specific environments, if these are specified on the command line, whether or not the project supports environment types. This is to preserve backwards compatibility for those who are using this command in non-interactive scripts. The server will then silently apply these changes to the entire environment type(s).
This PR instead converts environment-specific access to environment type-based access on the "client side" (within the CLI), rather than the server side. As before, in interactive mode, it will return an error if such environment-specific access has been specified, but now it attempts to provide an example of how to use the command with environment types. In non-interactive …

Translate environment ID to type when adding/changing a user

---

composer.json
composer.lock
src/Command/CommandBase.php
src/Command/CompletionCommand.php
src/Command/MultiCommand.php
src/Service/Api.php

- Separate project "stub" from full project representations to avoid using the stub information accidentally. Fixes inconsistent marking a user as the project "owner" in the users:list (users) command.
- Fixes the validation error when asked for a project ID interactively.

Rework fetching projects

---

src/Application.php

It was unclear to a user that the `-y` flag would accept default options even if they weren't boolean. Hopefully, the added help text would help in such a situation.

📝 Add clarity to yes flag

---

src/Command/Variable/VariableCreateCommand.php

Related to #1002
Awkwardly the "default" is compared with the value on the command line [here](https://github.com/platformsh/console-form/blob/d8f14e280a75098997cdfc562ae95392c7ee02f9/src/Field/Field.php#L500) using `getParameterOption('environment')`, which doesn't account for `-e`. Here `getParameterOption()` has to be used because `$input->getOption('environment')` (which _would_ account for `-e`) doesn't let you distinguish between "no value supplied, default used" and "default value explicitly supplied".
So, providing a default for the option causes the inconsistency between the short and long options. The solution is to stop providing a default. The result is that the --environment/-e value will be picked up anyway and then the question won't be shown.

Fix inconsistency in variable:create between -e and --environment

---

src/Command/Environment/EnvironmentLogCommand.php

This feature was broken in v3.83.0 when the --instance (-I) option was added

Fix Dedicated env detection in the environment:logs (log) command

---

src/Command/Db/DbDumpCommand.php
src/Command/Db/DbSqlCommand.php
src/Service/Relationships.php

The mysql/mariadb/oracle-mysql [services](https://docs.platform.sh/add-services/mysql.html) can be configured with custom `schemas`, which the CLI lists to find the default schema name for dumping a database in the `db:dump` command, if `--schema` is not supplied.
But the [postgresql](https://docs.platform.sh/add-services/postgresql.html) service is configured with custom `databases`, not `schemas`.

Fix listing custom schema (database) names for postgresql

---

src/Application.php
src/Command/MultiCommand.php

This instantiates a new Application for running commands via "multi", which means a new service container and new services for input and output will be used, and configureIO() will run again for processing non-interaction flags.

Fix parsing of non-interaction flags in the "multi" command

---

src/Command/Environment/EnvironmentXdebugCommand.php
src/Local/ApplicationFinder.php

Closes #1190 
A PHP 8 TypeError is being thrown when applications.yaml holds configuration of the wrong type (an application must be an object). The error is not an \Exception so it cannot easily be caught in the PHP < 7 compatible logic for hiding the Xdebug command when the project is not PHP. This PR makes the error an InvalidConfigException.

Avoid a TypeError when reading invalid applications.yaml configuration

---

composer.json
composer.lock
src/Service/ActivityMonitor.php

Fixes three problems:
1. activities can carry on waiting on progress indefinitely without appearing to receive new log messages
2. the activity log is curtailed
3. a warning in certain PHP versions (possibly just 7.4): `Warning: stream_select(): cannot cast a filtered stream on this system`

Improve activity log monitoring: re-fetch the log and remove stream_select()

---

config.yaml
src/Command/CommandBase.php
src/Service/Config.php
src/Util/OsUtil.php

* Add notification if both CLIs are installed
If the user has both the New CLI and the Legacy CLI installed and the Legacy CLI has execution precendence because of the `PATH` config, a warning is displayed.
* Add migrate prompt for the new CLI
The migrate prompt is disabled in the following cases:
* CLIs for white-labels other than Platform.sh
* CI systems
* When the CLI is run in the new wrapper
* Better use config for custom Wrapped functionality

Help users migrate to the new CLI

---

box.json

Exclude unnecessary libphonenumber data from Phar build

---

src/Command/CommandBase.php

Closes #1215 and closes #1216 (duplicate), but this is a dirty fix

Follow symlinks when checking for multiple CLI instances

---

src/Command/Integration/IntegrationCommandBase.php

Based on the [API](https://api.platform.sh/docs/#tag/Third-Party-Integrations/operation/create-projects-integrations) and the Console, it's possible to add a base URL for GitHub integrations, but the CLI seemed to restrict it. Adding it as possible for GitHub integrations.

Allow base URLs for GitHub integration

---

dist/installer.php
src/Command/CommandBase.php
src/Service/Config.php

Reads the following environment variables to suppress the warning about migrating to the new CLI installation method:
- PLATFORMSH_CLI_NO_LEGACY_WARNING=1
- IS_DDEV_PROJECT=true
- LANDO_INFO=anything
(in addition to the other currently supported variables which are `CI`, `BUILD_NUMBER` and `RUN_ID`)
Also accepts a command-line option `--no-legacy-warning`, e.g.
```sh
curl url/to/installer.php | php -- --no-legacy-warning
```

Provide more ways to suppress the legacy warning

---

src/Command/Environment/EnvironmentDrushCommand.php
src/Command/Local/LocalDrushAliasesCommand.php
src/Local/BuildFlavor/Drupal.php

This seems to occur when the home directory is recognised as a project, and isDrupal is running unnecessarily. This commit avoids performing the check unnecessarily while in the home directory, and sets Symfony to ignore unreadable directories while iterating.

Fix RecursiveDirectoryIterator UnexpectedValueException

---

src/Command/Project/ProjectCreateCommand.php
src/Command/Variable/VariableCommandBase.php

Relates to #1002 
Some optional questions will be omitted. The options are still available on the
command-line, and are not deprecated, but will no longer be asked in interactive
mode. These are:
* the --plan, --environments and --storage in the project:create command
* --json, --sensitive, --enabled, --prefix, --inheritable, --visible-build, and
--visible-runtime in the variable:create command

Ask fewer questions in project:create and variable:create forms

---

src/Command/Integration/IntegrationCommandBase.php

It seems that adding GitHub integrations was broken in #1221 by making --base-url required unintentionally.
N.B. with apologies for the potential compatibility break, this changes the
option name --base-url to --bitbucket-url for Bitbucket Server integrations,
which was necessary to fix the bug with GitHub and GitLab.

Do not require --base-url for GitHub and GitLab integrations

---

README.md
bin/platform
src/Command/CommandBase.php

Fixing deprecation notices isn't going to happen in v4 because it would break compatibility with older versions of PHP. These notices are not helpful for non-maintainers. This PR suppresses deprecation notices unless:
- debug mode is enabled (with `-vvv`), and
- an environment variable is set: `PLATFORMSH_CLI_REPORT_DEPRECATIONS=1`

Suppress deprecation notices by default

---

src/Application.php
src/Command/Metrics/AllMetricsCommand.php
src/Command/Metrics/CpuCommand.php
src/Command/Metrics/CurlCommand.php
src/Command/Metrics/DiskUsageCommand.php
src/Command/Metrics/MemCommand.php
src/Command/Metrics/MetricsCommandBase.php
src/Model/Metrics/Field.php
src/Model/Metrics/Query.php
src/Model/Metrics/Sketch.php
src/Model/Metrics/TimeSpec.php
src/Service/Api.php

This adds support for:
* Reading CPU and memory metrics (and all metrics at once in the `metrics` command).
* Viewing metrics for all services at once.
* Viewing temporary disk usage (as well as persistent).
* A `metrics:curl` command to help debug the API for an environment's metrics (intended for internal use; hidden from the command list).
It also changes the output of the `disk` command, which could require updates to scripts for compatibility:
* New *default* columns "Service" (service) and "/tmp %" (tmp_percent). The default columns are now: timestamp, service, used, limit, percent, ipercent, and tmp_percent.
* The command reports data for multiple services by default, if no --service (-s) option is given.
* The --type and --service options can support selecting multiple services …

Add new metrics commands: `metrics`, `cpu`, and `mem`

---

composer.json
composer.lock
src/Application.php
src/Command/Environment/EnvironmentPauseCommand.php
src/Command/Environment/EnvironmentResumeCommand.php

Development environments are automatically paused after two weeks of inactivity to save resources and reduce carbon emissions.
These commands add some manual control.

Add env:pause and env:resume commands

---

src/Command/CommandBase.php
src/Service/SelfUpdater.php

Addresses #1276 in the sense that automatically checking for updates requires the phar's directory to be writable, which is a workaround because of how the humbug/phar-updater library works:
https://github.com/humbug/phar-updater/blob/e5a5da3dc3344031271157c7f10b0fa04afffa9b/src/Updater.php#L467-L470
Ideally updating is now intended to be via the newer [wrapper](https://github.com/platformsh/cli) and package management, etc.

Only check for updates if the containing directory is writable

---

src/Command/Environment/EnvironmentScpCommand.php
src/Command/Environment/EnvironmentSshCommand.php
src/Model/Host/RemoteHost.php
src/Service/Ssh.php

A command with multiple arguments can be provided to `platform ssh` via `--`
```sh
platform ssh -- sed -n '/20\/Jul\/2023\:09\:40/, /20\/Jul\/2023\:09\:45/p' /var/log/access.log
```
Currently this is incorrectly quoted when forwarded over SSH

Improve SSH argument quoting

---

composer.json
composer.lock
src/Command/CommandBase.php
src/Command/CompletionCommand.php
src/Service/Api.php

This provides
```sh
-e .
```
as a shortcut for
```sh
-e "$(platform project:info default_branch)"
```
And it prevents looking up a resource (like an environment) with the ID "." or "..", which should not be considered valid, but currently selects the collection (e.g. the environments list) or the parent resource (e.g. the project) respectively.

Allow "." to select the default environment

---

src/Command/Activity/ActivityCancelCommand.php
src/Command/Environment/EnvironmentResumeCommand.php
src/Service/ActivityMonitor.php

- Prioritize displaying the log if there is one non-integration activity
- Add a newline before waiting
- Standardize how activity descriptions are displayed

Improve activity log formatting

---

config.yaml
src/Command/CommandBase.php
src/Command/Domain/DomainAddCommand.php
src/Command/Domain/DomainCommandBase.php
src/Command/Domain/DomainDeleteCommand.php
src/Command/Domain/DomainListCommand.php
src/Model/EnvironmentDomain.php

* Update for compatibility with project version 22 (omit the `type` parameter).
* Change `--replace` to `--attach`.
* Present an interactive choice of domains for `--attach` where relevant.
* Remove mention of "beta" in the messaging, when the feature for non-production environment domains is not enabled.
* Warn about attached domains when deleting a production domain.

Improve dev domains support

---

src/Command/Mount/MountDownloadCommand.php
src/Command/Mount/MountUploadCommand.php
src/Service/Rsync.php

Use --include before --exclude in rsync commands

---

config-defaults.yaml
src/Command/CommandBase.php
src/Command/Environment/EnvironmentPushCommand.php
src/Exception/RootNotFoundException.php

Improvements to the `push` command:
- Allow the current directory not to be mapped to a project - it need only be a Git repository.
- Also allow pushing to a different project (other than the one mapped to the directory).
- Only add or change the Git remote if `--set-upstream` is given. Recommend `set-remote` otherwise.
- State what will happen and then ask for confirmation before pushing in all interactive cases (not just when pushing to production).
- Use Git Push Options if available to activate the environment or set its parent (disabled by default).

Allow the push command to work before setting a remote project

---

src/Command/Metrics/MetricsCommandBase.php

Replace it with a maximum number of intervals (100)

Remove the minimum interval in metrics commands

---

config-defaults.yaml
src/Command/Environment/EnvironmentPushCommand.php
src/Model/Host/RemoteHost.php
src/Service/Git.php
src/Service/Relationships.php
src/Service/RemoteEnvVars.php
src/Service/Shell.php

* Add a configuration option `detection.push_deploy_error_messages` which lists messages that indicate a deployment error, e.g. "Error building project" or "Environment redeployment failed".
* If one of these error messages is found in the `git push` stderr log, report it and return a non-zero (failure) exit code, `87`.
* Note this is only possible on the push that causes the initial error; a subsequent push without a new commit would result in "Everything up-to-date" and a zero (success) exit code.

Check the git push log for deployment errors

---

src/Command/Resources/ResourcesSetCommand.php

Currently profile sizes must match exactly, with an exception of those prefixed by a dot ".5" being assumed as "0.5", etc.
This PR replaces this with PHP's loose comparison, which compares numeric strings like this as [floats](https://www.php.net/manual/en/language.types.float.php), meaning "4.0" matches "4" (and vice versa), ".5" still matches "0.5", and  "4.0000000000000001" also matches "4" (and an empty string would match "0", not that there is a size zero).
It has a side effect of making the code look a bit (I believe) simpler.

Loosely validate profile sizes in resources:set command

---

config-defaults.yaml
src/Command/Project/ProjectCreateCommand.php

Remove service.available_plans config, so there is no static list of plans. The plans list is fetched either from the organization setup options (the `/organizations/{id}/setup/options` API, if `api.organizations` is enabled), or from the `/plans` API.

Simplify plans configuration for the project:create (create) command

---

src/Command/Environment/EnvironmentActivateCommand.php
src/Command/Environment/EnvironmentPushCommand.php

* Fixes "push --activate": when the environment is paused activation will not be attempted (it will automatically reactivate on deployment).
* Fixes the "environment:activate" error message when the environment is paused. When possible it will now prompt for resuming the environment.

Handle the inability to reactivate paused environments

---

src/Command/ClearCacheCommand.php
src/Command/CommandBase.php
src/Command/Environment/EnvironmentBranchCommand.php
src/Command/Environment/EnvironmentRelationshipsCommand.php
src/Command/Integration/Activity/IntegrationActivityListCommand.php
src/Command/Metrics/AllMetricsCommand.php
src/Command/Organization/OrganizationSubscriptionListCommand.php
src/Command/Organization/User/OrganizationUserListCommand.php
src/Command/Self/SelfUpdateCommand.php

If the command has (visible) aliases, pick the first alias as the "preferred name" of the command to display in the "Usage" and "Examples" section of the help. This also cleans up aliases of some commands for consistency.

Show simpler command names in help (usage + examples)

---

src/Command/Project/ProjectCreateCommand.php

- Hide timeout options in help
- Wait and retry while fetching the project
- Recommend the "get" command afterwards
- Avoid fetching /regions twice

Improve project:create (create) command

---

src/Command/Resources/ResourcesSetCommand.php

Default to size 0.5, disk 512 MB when setting resources

---

config-defaults.yaml
src/Command/Resources/ResourcesGetCommand.php
src/Command/Resources/ResourcesSetCommand.php

Show a link to resources docs in command help

---

composer.json
composer.lock
config-defaults.yaml
services.yaml
src/Command/Auth/AuthInfoCommand.php
src/Service/Api.php
src/Service/Config.php
src/Service/FileLock.php
src/SshCert/Certifier.php

This guards against most of the race condition bugs that occur while running
multiple instances of the CLI in parallel. It doesn't fix all of them.

Lock while generating certificates or refreshing tokens

---

src/Command/Resources/ResourcesSetCommand.php

Since the current API does not provide a way to stop an update, this might lead in a state where the environment is not working and even doing forks will initialize new environment in this broken state.
This PR tries to calculate if the requested update will exceed the current user limit and if it does, it stops the operation. In case the user wants to proceed, they can use the `--force` argument.

Stop the user in case they add resources that exceed their limit

---

src/Command/CommandBase.php
src/Command/CompletionCommand.php
src/Command/Environment/EnvironmentPushCommand.php
src/Service/Api.php

Fixes a regression introduced in legacy-cli v4.11.0 (#1342), in which the default environment is not picked for the `ssh` command and others (any commands where the list of environment choices is filtered in some way).

Fix: always try to pick a default environment for the interactive choice

---

src/Command/CommandBase.php

Reopening #1335 which was prematurely merged and then reverted as it did not check for `$this->input->hasOption()`

Forward dynamic options when running a subcommand

---

src/Command/WebCommand.php
src/Command/WelcomeCommand.php
src/Service/Api.php

Alternative to #1364 
This one shows more information, but is slower and more convoluted

Display the correct Console URL in the welcome command

---

config-defaults.yaml
src/Command/CommandBase.php
src/Command/Local/LocalDrushAliasesCommand.php

Allows automatic Drush alias functionality to be turned off with
```sh
export PLATFORMSH_CLI_APPLICATION_DRUSH_ALIASES=0
```
or
```sh
echo 'application: {drush_aliases: false}' >> ~/.platformsh/config.yaml
```

Allow auto drush aliases to be turned off via a feature flag

---

config-defaults.yaml
config.yaml
src/Command/ApiCurlCommand.php
src/Command/Auth/AuthInfoCommand.php
src/Command/Auth/AuthTokenCommand.php
src/Command/Auth/VerifyPhoneNumberCommand.php
src/Command/CommandBase.php
src/Command/Organization/OrganizationCreateCommand.php
src/Command/Organization/OrganizationCurlCommand.php
src/Command/User/UserAddCommand.php
src/Service/Api.php
src/Service/Config.php
src/Service/SshDiagnostics.php

* Requires the config key `api.base_url` to be set everywhere
* Removes the config keys `api.auth` and `api.invitations`; assumes these APIs are enabled everywhere
* Removes now irrelevant backwards compatibility code
Related to https://github.com/platformsh/platformsh-client-php/pull/87

Remove support for pre-"Auth" APIs

---

composer.json
composer.lock
config-defaults.yaml
src/Command/CompletionCommand.php
src/Command/User/UserAddCommand.php
src/Command/User/UserCommandBase.php
src/Command/User/UserDeleteCommand.php
src/Command/User/UserGetCommand.php
src/Command/User/UserListCommand.php
src/Service/Api.php

Use the new user-access API

---

src/Service/SshConfig.php

The certificate may be available and valid, even if the `platform ssh-cert:load --refresh-only` command fails for whatever reason. If the command fails then the `Match ... exec ...` line will cause subsequent statements not to apply. This PR adds a `Host <hostname>` cancellation line, after the `Match ... exec ...`.

Include the SSH certificate in config even if refresh fails

---

config-defaults.yaml
config.yaml
src/Command/SshCert/SshCertLoadCommand.php
src/Command/WelcomeCommand.php
src/Service/Config.php
src/Service/Ssh.php
src/Service/SshConfig.php
src/Service/SshDiagnostics.php
src/SshCert/Certifier.php

Adds an `ssh.cert_only` config option which if enabled means only the certificate will be included in config, if a certificate exists, and not the user's "default" public key files (~/.ssh/id_rsa etc.). This is disabled by default. It can be enabled in the config file or in the environment (e.g. `export PLATFORMSH_CLI_SSH_CERT_ONLY=1`).

Only use the SSH certificate if available

---

config-defaults.yaml
services.yaml
src/Command/Db/DbSqlCommand.php
src/Command/Environment/EnvironmentPushCommand.php
src/Command/Environment/EnvironmentSshCommand.php
src/Command/Environment/EnvironmentXdebugCommand.php
src/Command/Service/MongoDB/MongoShellCommand.php
src/Command/Service/RedisCliCommand.php
src/Command/SshCert/SshCertLoadCommand.php
src/Service/Config.php
src/Service/Git.php
src/Service/Ssh.php
src/Service/SshConfig.php
src/Service/SshDiagnostics.php

* Adds a configuration setting `ssh.options` allowing arbitrary SSH options to be appended.
* Adds an option `--option` (`-o`) in the `ssh` command for additional options.
* Passes on options to SSH without validating or changing them.
* Stops setting the "RequestTTY force" option for SSH in the `ssh` command.  
This change is because this option is [potentially irritating](https://serverfault.com/a/593419) for scripting users and unnecessary for others.  
The previous behavior can be restored with either:
- `-o 'RequestTTY force'` or
- `export PLATFORMSH_CLI_SSH_OPTIONS='RequestTTY force'`
* Allow SSH to continue even after failing to write configuration files.
* Do not (re)write config when running `ssh-cert:load --refresh-only`.

Stop setting "RequestTTY force" for SSH

---

composer.json
composer.lock
src/Command/Organization/User/OrganizationUserListCommand.php

Adds `--count` and `--sort` options to the org:users command (`--count 0` to fetch all pages).
No specific `--page` option is provided as the API provides opaque cursor-based pagination which is powerful but could look confusing in this context.

Add pagination to the org:users command

---

src/Service/Api.php

Fixes https://github.com/platformsh/cli/discussions/166 / https://github.com/platformsh/cli/issues/162
This code was incorrectly removed in legacy CLI v4.12.0 via https://github.com/platformsh/legacy-cli/commit/47cade7748f91f271a9cd18a34285c71f26f8b3f

Fix projects being fetched via an old hostname

---

config-defaults.yaml
src/Command/CommandBase.php
src/Command/SshCert/SshCertInfoCommand.php
src/Command/SshCert/SshCertLoadCommand.php
src/Service/Ssh.php
src/Service/SshDiagnostics.php
src/SshCert/Certificate.php
src/SshCert/Certifier.php

This PR alters certificate refreshing to make it no longer regenerate the
SSH key pair every time. It adds a config parameter `ssh.cert_key_ttl` (default
86400) for the lifetime in seconds of a key pair. Set to 0 for the key pair
never to expire or -1 for it to be regenerated every time the certificate is
refreshed. This can be overridden in the environment variable
`PLATFORMSH_CLI_SSH_CERT_KEY_TTL`.
This PR also ensures that new keys are written (or rather, renamed into
place) much closer to the time of saving the new certificate.
These changes will reduce the chance of a key pair being regenerated while it is
being read by another program (like SSH), for example if an SSH connection is
made at exactly the same time as another CLI process that is refreshing the
certificate. Three files …

Reduce SSH errors when connections and certificate refreshes are made in parallel

---

src/Command/Metrics/MetricsCommandBase.php

Test for Upsun with:
```sh
curl -s https://raw.githubusercontent.com/platformsh/cli/main/internal/config/upsun-cli.yaml > /tmp/upsun-cli.yaml
curl -s https://pr-1402-x5xx7sy-mpaw4nkgdwaea.eu-2.platformsh.site/platform.phar > /tmp/platform-pr-1402.phar
alias upsun='CLI_CONFIG_FILE=/tmp/upsun-cli.yaml php /tmp/platform-pr-1402.phar'
upsun cpu
upsun mem
```

Fix metrics for multi-instance grid hosting

---

src/Command/Environment/EnvironmentSshCommand.php
src/Command/Environment/EnvironmentXdebugCommand.php
src/Command/SshCert/SshCertLoadCommand.php
src/Model/Host/RemoteHost.php
src/Service/Git.php
src/Service/Rsync.php
src/Service/Ssh.php
src/Service/SshConfig.php
src/Service/SshDiagnostics.php

Aims to improve performance (only on POSIX shells) when running the `ssh` and related commands, by modifying the generated SSH config so that it will not run the `ssh-cert:load` command unnecessarily, using an environment variable to determine when SSH is being run through the CLI. Seems to save 100-200ms in cursory test.

Skip rerunning SSH cert check when SSHing from the CLI

---

src/CredentialHelper/Manager.php

The docker-credential-helpers are now distributed as binaries rather than zip or tgz archives.

Fix "Failed to extract zip" on Windows (by updating credential helpers)

---

src/Command/Backup/BackupRestoreCommand.php
src/Command/CommandBase.php
src/Command/Environment/EnvironmentActivateCommand.php
src/Command/Environment/EnvironmentBranchCommand.php
src/Command/Environment/EnvironmentMergeCommand.php
src/Command/Environment/EnvironmentPushCommand.php

If the api.sizing configuration flag is enabled, this adds the option to the following affected commands, in addition to the existing option on the `environment:push` (push) command. The option can only be used with projects that support the flexible resources API. It sets the strategy to be used for picking the size of new resources on the target environment: `parent`, `child`, `default`, `minimum`, or `manual`.
Affected commands:
* `backup:restore`
* `environment:activate`
* `environment:branch` (`branch`)
* `environment:merge` (`merge`)
* `environment:synchronize` (`sync`)
Part of #1384 
Test for Upsun with:
```
curl -s https://raw.githubusercontent.com/platformsh/cli/main/internal/config/upsun-cli.yaml > /tmp/upsun-cli.yaml
curl -s …
```

Add --resources-init option to five more commands

---

config-defaults.yaml
config.yaml
src/Service/Config.php
src/Service/Identifier.php
tests/ConfigTest.php
tests/data/mock-cli-config.yaml

This also removes the config key `detection.use_site_headers`.

Move config service.header_prefix to detection.cluster_header and make it optional

---

src/Command/Db/DbDumpCommand.php
src/Command/Db/DbSizeCommand.php
src/Command/Db/DbSqlCommand.php
src/Service/Relationships.php

MariaDB introduced the `mariadb` command as a symlink in [version 10.4.6](https://mariadb.com/kb/en/mariadb-1046-release-notes/) and then made it a separate binary in [10.5.2](https://mariadb.com/kb/en/mariadb-1052-release-notes/) with `mysql` being a symlink. Apparently and unfortunately the Debian mariadb-client package doesn't include the `mysql` symlink; the `mariadb-client-compat` package is needed on top.

Use MariaDB-specific command names in "db:" commands

---

src/Command/Metrics/MetricsCommandBase.php

Avoids "Failed to determine the deployment type" on environments with new or nonstandard deployment target types.

Fix deployment type detection in metrics commands

---

composer.json
composer.lock
src/Model/Host/RemoteHost.php
src/Service/SshDiagnostics.php

* Respect user sso_enabled property.
* Remove extra blank line.
* Fix stray "Then" when MFA URL not configured.

Improve SSH/MFA error message

---

composer.json
composer.lock
src/Application.php
src/Command/Resources/Build/BuildResourcesGetCommand.php
src/Command/Resources/Build/BuildResourcesSetCommand.php
src/Command/Resources/ResourcesCommandBase.php
src/Command/Resources/ResourcesGetCommand.php
src/Command/Resources/ResourcesSetCommand.php
src/Command/Resources/ResourcesSizeListCommand.php
src/Service/QuestionHelper.php

New commands:
* `resources:build:get` (aliased to `build-resources:get`)
* `resources:build:set` (aliased to `build-resources:set`)
Test for Upsun with:
```
curl -s https://raw.githubusercontent.com/platformsh/cli/main/internal/config/upsun-cli.yaml > /tmp/upsun-cli.yaml
curl -s https://pr-1447-ryc5tsy-mpaw4nkgdwaea.eu-2.platformsh.site/platform.phar > /tmp/platform-pr-1447.phar
alias upsun='CLI_CONFIG_FILE=/tmp/upsun-cli.yaml php /tmp/platform-pr-1447.phar'
```
Test requirements are the same as the legacy CLI installation requirements:
> an operating system supported by PHP (Linux, OS X, or Windows) and PHP (5.5.9 or higher) installed, with the following extensions: curl, json, pcre, and phar.

Add commands to get and set build resources

---

resources/oauth-listener/index.php
src/Command/Auth/BrowserLoginCommand.php

Persists the exact redirect URI that was used, between the authorize request and the token request.

Allow local OAuth listener to succeed on an alternative port

---

src/Service/SshConfig.php

Fish does not appear to provide an easy method to test for the variable not existing that does not involve double quotes. We need to avoid double quotes because OpenSSH does not support escaping them inside the "Match ... exec" command.

Fix SSH error in fish shell: "Missing argument at index 3"

---

composer.json
composer.lock
src/Command/Backup/BackupRestoreCommand.php

Closes https://github.com/platformsh/cli/issues/190
```
Usage:
upsun backup:restore [--target TARGET] [--branch-from BRANCH-FROM] [--no-code] [--no-resources] [--resources-init RESOURCES-INIT] [-p|--project PROJECT] [-e|--environment ENVIRONMENT] [-W|--no-wait] [--wait] [--] [<backup>]
Arguments:
backup                               The ID of the backup. Defaults to the most recent one
Options:
--target=TARGET                  The environment to restore to. Defaults to the backup's current environment
--branch-from=BRANCH-FROM        If the --target does not yet exist, this specifies the parent of the new
environment
--no-code                        Do not restore code, only data.
--no-resources                   Do not override the target's existing resource settings. …
```

Update backup:restore command resources options

---

src/Command/Environment/EnvironmentPushCommand.php

* Fix setting the type during push.
* Omit the parent and type from the git push options if they are not specified. This avoids an error when pushing to a non-default branch for the second time, when the default branch has no code.

Improve --parent and --type options for the push command

---

src/Service/CurlCli.php

Produces output like:
```
> GET /users/me HTTP/2
> Host: api.platform.sh
> User-Agent: curl/8.2.1
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
> Authorization: Bearer [credentials]
```

Auto-censor the Authorization header in curl commands

---

config-defaults.yaml
src/Service/SshConfig.php

Restore the previous behavior by setting the environment variable `PLATFORMSH_CLI_SSH_CONVERT_WINDOWS_PATHS` to `0`.

Convert Windows filenames for SSH config

---

src/Service/Api.php

Requests /environments with double the default API request timeout (60 rather than 30 seconds). This is by far the slowest API endpoint, arguably for good reasons, but it's also the entrypoint for a lot of commands, and the current default timeout is being reached quite frequently.

Extend the request timeout for /environments requests

---

config-defaults.yaml
src/Service/Ssh.php
src/Service/SshConfig.php

Restore the previous version's behavior by setting the environment variable `PLATFORMSH_CLI_SSH_WINDOWS_PATHS=raw` (or replace `PLATFORMSH_CLI_` with the correct vendor prefix)

Add Unix paths for OpenSSH on Windows

---

src/Service/Relationships.php

Adds a special case for Solr URLs (fixes #1443)
and also PostgreSQL - changing `pgsql://` to `postgresql://`

Improve formatting of Solr and PostgreSQL URLs

---

config-defaults.yaml
config.yaml
src/Command/CommandBase.php
src/Command/Team/TeamCommandBase.php
src/Command/Team/TeamListCommand.php
src/Command/User/UserListCommand.php
src/Service/Api.php
src/Util/Sort.php

The `team:list` (`teams`) command will now filter the teams list to those with
access to the selected project, if any. The project is selected in the normal
way, e.g. by `--project` (`-p`), or the current Git repository.
Use the `--all` option to list all the teams in the organization.
Add the `granted_at` column (`--columns +granted_at`) to see when the team was
added to the project.
This MR also adds a bit more local caching for organization data.

Support listing teams for a single project

---

src/Command/SshCert/SshCertLoadCommand.php
src/Service/SshConfig.php

This partially reverts 29a92850a2ce8a4f583e23bba75dcf1fdaad44c3

Re-allow output from "ssh-cert:load --refresh-only", now that quiet mode works

---

src/Service/Api.php

The cache should clear after a project is created, updated or deleted in the CLI. Note the cache also expires after 10 minutes by default.

Fix project list cache not clearing automatically

---

src/Command/Project/ProjectCreateCommand.php
src/Service/Api.php

Clarify project creation errors, by checking whether the organization is allowed to create a project in advance.
Integration tests are in https://github.com/platformsh/cli/pull/216

Check the organization /can-create API before creating a project

---

composer.lock
go-tests/environment_deploy_test.go
go-tests/go.mod
src/Application.php
src/Command/Activity/ActivityCommandBase.php
src/Command/Environment/EnvironmentDeployCommand.php
src/Service/ActivityLoader.php
src/Service/ActivityMonitor.php

Add environment deploy command and staged activities

---

src/Command/Environment/EnvironmentDeployCommand.php

The `deploy` alias conflicts slightly with an old idea, that `deploy` should be an alias of `push`.
The new command does "deploy staged changes", which is clearly a deploy action, whereas pushing is not (and was never) necessarily about deploying. So I think it's decent naming.
But there is a potential risk of confusion / "wtf", and I'd like to be conservative with the new feature.

Remove "deploy" alias from env:deploy command

---

src/Service/Api.php

fix: let getAutoscalingSettings return empty settings when autoscaling is not available

---

src/Command/Environment/EnvironmentActivateCommand.php

The question is open (for the future) whether it makes sense to check this on an inactive environment.

Fix "This environment is inactive" during activation if the deployment cannot be fetched
